project_id = "yhzurkotubkkaokhtmsb"

[functions.send-otp]
verify_jwt = false

[functions.search-users]
verify_jwt = false

[functions.search-external-users]
verify_jwt = false

[functions.receive-chat-message]
verify_jwt = false

[functions.send-chat-message]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.receive-freelance-selected]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.receive]
verify_jwt = false

[functions.create-account]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.delete-driver]
verify_jwt = false

[functions.receive-company-factory]
verify_jwt = false

[functions.get-conversation-participant]
verify_jwt = false

[functions.receive-job-status]
verify_jwt = false

[functions.receive-bidding-job]
verify_jwt = false

[functions.send-bid]
verify_jwt = false

[functions.create-test-user]
verify_jwt = false

[functions.receive-bid-status]
verify_jwt = false

[functions.register-driver]
verify_jwt = false

[functions.upload-registration-file]
verify_jwt = false

[functions.get-freelance-drivers]
verify_jwt = false

[functions.update-freelance-driver]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.create-tracking-room]
verify_jwt = false

[functions.update-truck-position]
verify_jwt = false

[functions.chatbot-assistant]
verify_jwt = false

[functions.list-tickets]
verify_jwt = false

[functions.check-new-jobs]
verify_jwt = false

[functions.get-notifications]
verify_jwt = false

[functions.create-bid]
verify_jwt = false

[functions.zegocloud-token]
verify_jwt = false

[functions.apply-security-migration]
verify_jwt = false
