import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'th';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    const translations = language === 'th' ? thTranslations : enTranslations;
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Thai translations
const thTranslations: Record<string, string> = {
  // Settings Page
  'settings.title': 'ตั้งค่า',
  'settings.profile': 'โปรไฟล์',
  'settings.personal_info': 'ข้อมูลส่วนตัว',
  'settings.account': 'บัญชี',
  'settings.vehicle_info': 'ข้อมูลรถ',
  'settings.general': 'ทั่วไป',
  'settings.notifications': 'การแจ้งเตือน',
  'settings.notifications_enabled': 'เปิดแจ้งเตือน',
  'settings.notifications_disabled': 'ปิดแจ้งเตือน',
  'settings.about': 'ข้อมูลเกี่ยวกับแอป',
  'settings.language': 'ภาษา',
  'settings.terms': 'เงื่อนไขการใช้บริการและนโยบาย',
  'settings.contact': 'ติดต่อศูนย์',
  'settings.sign_out': 'ออกจากระบบ',
  'settings.sign_out_confirm': 'คุณต้องการออกจากระบบหรือไม่?',
  'settings.sign_out_description': 'การออกจากระบบจะทำให้คุณต้องล็อกอินเข้าสู่ระบบอีกครั้ง ในครั้งถัดไป กรุณายืนยันออกจากระบบ',
  'settings.cancel': 'ยกเลิก',
  
  // Language Page
  'language.title': 'ภาษา',
  'language.thai': 'ภาษาไทย',
  'language.english': 'English',
  
  // Bottom Navigation
  'nav.home': 'หน้าแรก',
  'nav.dashboard': 'แผงควบคุม',
  'nav.chat': 'แชท',
  'nav.settings': 'ตั้งค่า',
  
  // Home Page
  'home.search': 'ค้นหา',
  'home.recommended': 'งานแนะนำสำหรับคุณ',
  'home.items': 'รายการ',
  'home.error_load': 'เกิดข้อผิดพลาด',
  'home.error_load_desc': 'ไม่สามารถโหลดข้อมูลงานได้',
  'home.error_accept': 'ไม่สามารถรับงานได้',
  'home.accept_success': 'รับงานสำเร็จ',
  'home.accept_success_desc': 'คุณได้รับงาน',
  'home.greeting': '👋',
  'home.sunday': 'วันอาทิตย์',
  'home.monday': 'วันจันทร์',
  'home.tuesday': 'วันอังคาร',
  'home.wednesday': 'วันพุธ',
  'home.thursday': 'วันพฤหัสบดี',
  'home.friday': 'วันศุกร์',
  'home.saturday': 'วันเสาร์',
  'home.current_jobs': 'งานปัจจุบัน',
  'home.bidding': 'เสนอราคา',
  'home.income': 'รายได้',
  'home.job_history': 'ประวัติงาน',
  'home.sign_out_confirm': 'คุณต้องการออกจากระบบหรือไม่?',
  'home.sign_out_desc': 'การออกจากระบบจะทำให้คุณต้องล็อกอินเข้าสู่ระบบอีกครั้ง ในครั้งถัดไป กรุณายืนยันออกจากระบบ',
  'home.sign_out_btn': 'ออกจากระบบ',
  'home.cancel': 'ยกเลิก',
  
  // Job Card
  'job.order_code': 'รหัสออเดอร์',
  'job.employer': 'ผู้จ้าง',
  'job.domestic': 'ขนส่งภายในประเทศ',
  'job.international': 'ขนส่งภายนอกประเทศ',
  'job.inbound': 'ขาเข้า',
  'job.outbound': 'ขาออก',
  'job.origin': 'ต้นทาง',
  'job.destination': 'ปลายทาง',
  'job.equipment': 'อุปกรณ์ติดรถ',
  'job.safety': 'อุปกรณ์ Safety',
  'job.accept': 'รับงานนี้',
  'job.accepted': 'รับงานนี้แล้ว',
  
  // Confirm Job Dialog
  'confirm.title': 'ยืนยันการรับงาน',
  'confirm.order_code': 'รหัสออเดอร์',
  'confirm.employer': 'ผู้จ้าง',
  'confirm.message': 'หากคุณต้องการรับรถงานที่ "ยืนยัน"',
  'confirm.cancel': 'ยกเลิก',
  'confirm.confirm': 'ยืนยัน',
  
  // Job History Page
  'jobHistory.title': 'ประวัติงาน',
  'jobHistory.all': 'ทั้งหมด',
  'jobHistory.inProgress': 'กำลังส่ง',
  'jobHistory.completed': 'เสร็จสิ้น',
  'jobHistory.selectMonth': 'เลือกเดือน',
  'jobHistory.allMonths': 'ทุกเดือน',
  'jobHistory.january': 'มกราคม',
  'jobHistory.february': 'กุมภาพันธ์',
  'jobHistory.march': 'มีนาคม',
  'jobHistory.april': 'เมษายน',
  'jobHistory.may': 'พฤษภาคม',
  'jobHistory.june': 'มิถุนายน',
  'jobHistory.july': 'กรกฎาคม',
  'jobHistory.august': 'สิงหาคม',
  'jobHistory.september': 'กันยายน',
  'jobHistory.october': 'ตุลาคม',
  'jobHistory.november': 'พฤศจิกายน',
  'jobHistory.december': 'ธันวาคม',
  'jobHistory.loading': 'กำลังโหลด...',
  'jobHistory.noData': 'ไม่พบประวัติงาน',
  'jobHistory.statusCompleted': 'เสร็จสิ้น',
  'jobHistory.statusDelivering': 'กำลังจัดส่ง',
  'jobHistory.statusAccepted': 'รับงานแล้ว',
  
  // Current Jobs Page
  'currentJobs.title': 'งานปัจจุบัน',
  'currentJobs.search': 'ค้นหา ชื่อ,ออเดอร์,รหัสออเดอร์',
  'currentJobs.empty': 'ยังไม่มีงานในตอนนี้',
  'currentJobs.viewDetails': 'ดูข้อมูลงาน',
  'currentJobs.filter': 'ตัวกรอง',
  'currentJobs.dateRange': 'วันเวลาที่รับมอบงาน',
  'currentJobs.startDate': 'วันที่เริ่มต้น',
  'currentJobs.endDate': 'วันที่สิ้นสุด',
  'currentJobs.clearFilter': 'ล้างค่า',
  'currentJobs.applyFilter': 'ค้นหา',
  'currentJobs.startJobDate': 'วันเริ่มงาน',
  'currentJobs.errorLoad': 'เกิดข้อผิดพลาด',
  'currentJobs.errorLoadDesc': 'ไม่สามารถโหลดข้อมูลงานได้',
  
  // Bidding Page
  'bidding.title': 'เสนอราคา',
  'bidding.biddingTab': 'เสนอราคา',
  'bidding.historyTab': 'ประวัติ',
  'bidding.noJobs': 'ไม่มีงานที่เปิดรับเสนอราคา',
  'bidding.placeBid': 'เริ่มเสนอราคา',
  'bidding.noHistory': 'ยังไม่มีประวัติการเสนอราคา',
  'bidding.bidAt': 'เสนอราคาเมื่อ',
  'bidding.statusPending': 'รอดำเนินการ',
  'bidding.statusAccepted': 'เสร็จสิ้น',
  'bidding.statusRejected': 'ปฏิเสธ',
  'bidding.monthLabel': 'กุมภาพันธ์',
  
  // Income Page
  'income.title': 'รายได้ของฉัน',
  'income.all': 'ทั้งหมด',
  'income.paid': 'ชำระแล้ว',
  'income.unpaid': 'ยังไม่ชำระ',
  'income.selectMonth': 'เลือกเดือน',
  'income.viewDetails': 'ดูข้อมูลงาน',
  'income.noData': 'ไม่มีข้อมูลรายได้',
  'income.noPaid': 'ไม่มีงานที่ชำระแล้ว',
  'income.noUnpaid': 'ไม่มีงานที่ยังไม่ชำระ',
  'income.errorLoad': 'เกิดข้อผิดพลาด',
  'income.errorLoadDesc': 'ไม่สามารถโหลดข้อมูลรายได้ได้',
  
  // Dashboard Page
  'dashboard.finance': 'การเงิน (ค่าใช้จ่าย)',
  'dashboard.finance_desc': 'ติดตามรายรับ, รายจ่าย ได้ง่าย',
  'dashboard.shipping': 'การจัดส่ง',
  'dashboard.shipping_desc': 'ตรวจสอบการจัดส่งของคุณ',
  'dashboard.customer': 'ลูกค้า',
  'dashboard.customer_desc': 'ดูข้อมูลลูกค้าของคุณ',
  'dashboard.product': 'สินค้า',
  'dashboard.product_desc': 'ดูข้อมูลประเภทสินค้า',
  'dashboard.view': 'ดู',

  // Finance Page
  'finance.title': 'การเงิน',
  'finance.day': 'วัน',
  'finance.month': 'เดือน',
  'finance.year': 'ปี',
  'finance.profit': 'กำไร',
  'finance.expenses': 'ค่าใช้จ่าย',
  'finance.total_income': 'รายได้ทั้งหมด',
  'finance.compare_year': 'เปรียบเทียบกับปี: 2566',
  'finance.buddhist_era': 'พ.ศ.',
  'finance.income': 'รายได้',
  'finance.pending_payments': 'รายได้ค้างชำระ',
  'finance.companies': 'บริษัท',

  // Shipping Page
  'shipping.title': 'การจัดส่ง',
  'shipping.all_types': 'ทุกประเภทการขนส่ง',
  'shipping.tractor': 'หัวลาก',
  'shipping.12wheels': '12 ล้อ',
  'shipping.10wheels': '10 ล้อ',
  'shipping.6wheels': '6 ล้อ',
  'shipping.4wheels': '4 ล้อ',
  'shipping.job_data': 'ข้อมูลงานจัดส่ง',
  'shipping.all_jobs': 'งานทั้งหมด',
  'shipping.success': 'สำเร็จ',
  'shipping.in_delivery': 'กำลังจัดส่ง',
  'shipping.cancelled': 'ยกเลิก',
  'shipping.by_region': 'การขนส่งแต่ละภาค',
  'shipping.north': 'ภาคเหนือ',
  'shipping.central': 'ภาคกลาง',
  'shipping.northeast': 'ภาคอีสาน',
  'shipping.east': 'ภาคตะวันออก',
  'shipping.west': 'ภาคตะวันตก',
  'shipping.south': 'ภาคใต้',

  // Customer Page
  'customer.title': 'ลูกค้า',
  'customer.top_5': '5 อันดับสูงสุด',
  'customer.jobs': 'งาน',

  // Product Page
  'product.title': 'สินค้า',
  'product.product_types': 'ประเภทสินค้า',
  'product.top_5': '5 อันดับสูงสุด',
  'product.jobs': 'งาน',
  
  // Search Page
  'search.title': 'ค้นหา',
  'search.search': 'ค้นหา',
  'search.results': 'ผลการค้นหา',
  'search.no_results': 'ไม่พบผลการค้นหา',
  'search.recent': 'คำค้นหาล่าสุด',
  'search.popular': 'คำค้นหายอดนิยม',
  'search.filter': 'ตัวกรอง',
  'search.filter_desc': 'กรองผลการค้นหา',
  'search.domestic': 'ขนส่งภายในประเทศ',
  'search.international': 'ขนส่งภายนอกประเทศ',
  'search.province': 'จังหวัด',
  'search.district': 'อำเภอ',
  'search.select_province': 'เลือกจังหวัด',
  'search.select_district': 'เลือกอำเภอ',
  'search.select_district_first': 'กรุณาเลือกจังหวัดก่อน',
  'search.price_range': 'ช่วงราคา (฿)',
  'search.min_price': 'ใส่ราคาต่ำสุด',
  'search.max_price': 'ใส่ราคาสูงสุด',
  'search.clear': 'ล้างค่า',
  'search.apply': 'ค้นหา',
  
  // Profile Page
  'profile.title': 'โปรไฟล์',
  'profile.first_name': 'ชื่อ',
  'profile.last_name': 'นามสกุล',
  'profile.phone': 'เบอร์โทรศัพท์',
  'profile.email': 'อีเมล',
  'profile.work_areas': 'อำเภอ หรือ จังหวัด ที่ถนัดหรือจังหวัดทั่วเป็นประจำ',
  'profile.price_range': 'เรทราคาวังงาน (฿)',
  'profile.change_avatar': 'ยืนยันการเปลี่ยนรูปโปรไฟล์',
  'profile.change_avatar_desc': 'คุณต้องการเปลี่ยนรูปโปรไฟล์เป็นรูปนี้หรือไม่?',
  'profile.confirm': 'ยืนยัน',
  'profile.cancel': 'ยกเลิก',
  'profile.uploading': 'กำลังอัพโหลด...',
  'profile.error_upload': 'ไม่สามารถอัพโหลดรูปภาพได้',
  'profile.error_update': 'ไม่สามารถอัพเดทโปรไฟล์ได้',
  'profile.success': 'สำเร็จ',
  'profile.success_desc': 'อัพเดทรูปโปรไฟล์แล้ว',
  
  // Account Page
  'account.title': 'บัญชี',
  'account.username': 'ชื่อผู้ใช้',
  'account.no_data': 'ไม่มีข้อมูล',
  'account.password': 'รหัสผ่าน',
  'account.delete': 'ลบบัญชี',
  'account.delete_confirm': 'คุณกำลังจะลบบัญชีใช่ไหม',
  'account.delete_desc': 'การลบบัญชีนี้จะเป็นการลบข้อมูลทั้งหมด',
  'account.delete_personal': 'ข้อมูลส่วนตัว',
  'account.delete_history': 'ประวัติการใช้บริการ',
  'account.delete_transactions': 'ข้อมูลธุรกรรมทั้งหมด',
  'account.delete_warning': 'หลังจากลบบัญชีแล้วจะไม่สามารถกู้คืนได้',
  'account.deleting': 'กำลังลบ...',
  'account.cancel': 'ยกเลิก',
  'account.delete_success': 'ลบบัญชีสำเร็จ',
  'account.delete_success_desc': 'บัญชีของคุณถูกลบเรียบร้อยแล้ว',
  'account.delete_error': 'เกิดข้อผิดพลาด',
  'account.delete_error_desc': 'ไม่สามารถลบบัญชีได้ กรุณาลองใหม่อีกครั้ง',
  
  // Terms Page
  'terms.title': 'เงื่อนไขการใช้บริการและนโยบาย',
  'terms.heading': 'Truckers  นโยบายความเป็นส่วนตัวของผู้ขับรถ',
  'terms.updated_date': 'มีผลบังคับเมื่อวันที่ 15 มกราคม 2567',
  'terms.collection_title': 'ข้อมูลที่เรารวบรวม',
  'terms.collection_intro': 'เรารวบรวมข้อมูลที่จำเป็นสำหรับการให้บริการแอป Truckers แก่ผู้ขับรถ ซึ่งรวมถึงข้อมูลที่คุณให้ไว้โดยตรงและข้อมูลที่เรารวบรวมจากการใช้แอป เช่น:',
  'terms.personal_data': 'ข้อมูลส่วนบุคคล :',
  'terms.personal_data_desc': 'เช่น ชื่อ, อีเมล, เบอร์โทรศัพท์, และข้อมูลบัญชีที่เกี่ยวข้องกับการขนส่ง',
  'terms.technical_data': 'ข้อมูลทางเทคนิค :',
  'terms.technical_data_desc': 'รวมถึงข้อมูลเกี่ยวกับการเดินทาง, ตำแหน่งที่ตั้ง (GPS), ความเร็ว, เส้นทางที่เลือก, เวลาเริ่มต้นและสิ้นสุดการขนส่ง',
  'terms.price_data': 'ข้อมูลราคา :',
  'terms.price_data_desc': 'รวมถึงหมายเลขทะเบียนรถ, ประเภทของรถ, และข้อมูลที่เกี่ยวข้องกับสภาพของรถบรรทุก',
  'terms.financial_data': 'ข้อมูลทางการเงิน :',
  'terms.financial_data_desc': 'ข้อมูลใช้สำหรับการชำระเงิน เช่น รายละเอียดบัญชีธนาคารหรือข้อมูลบัตรเครดิต',
  'terms.communication_data': 'ข้อมูลการสื่อสาร :',
  'terms.communication_data_desc': 'ข้อความ, การพูดคุย, หรือการติดต่อผ่านแอปที่เกี่ยวข้องกับการให้บริการ',
  'terms.usage_title': 'วิธีการใช้ข้อมูล',
  'terms.usage_intro': 'เราจะใช้ข้อมูลของคุณในหลายๆ ด้าน เช่น:',
  'terms.usage_1': 'การประมวลผลคำขอนส่งสินค้า',
  'terms.usage_2': 'การคำนวณค่าบริการและการชำระเงิน',
  'terms.usage_3': 'การปรับปรุงการให้บริการและการพัฒนาแอป',
  'terms.usage_4': 'การติดต่อคุณเพื่อให้ข้อมูลเกี่ยวกับสถานะการขนส่ง หรือแจ้งเตือน',
  'terms.usage_5': 'การปรับปรุงประสบการณ์การใช้งานของคุณ',
  'terms.usage_6': 'การปฏิบัติตามข้อกำหนดทางกฎหมาย',
  'terms.sharing_title': 'การแชร์ข้อมูล',
  'terms.sharing_intro': 'เราจะไม่แชร์ข้อมูลส่วนบุคคลของคุณกับบุคคลภายนอก ยกเว้นในกรณีดังต่อไปนี้:',
  'terms.sharing_provider': 'ผู้ให้บริการที่เราจ้าง:',
  'terms.sharing_provider_desc': 'บริษัทหรือบุคคลที่เราใช้บริการในด้านต่างๆ (เช่น บริการชำระเงิน, การวิเคราะห์ข้อมูล) ซึ่งมีข้อกำหนดความเป็นส่วนตัวที่ป้องกันข้อมูลของคุณ',
  'terms.sharing_legal': 'การปฏิบัติตามกฎหมาย:',
  'terms.sharing_legal_desc': 'ในกรณีที่เราถูกบังคับตามกฎหมาย เช่น การให้ข้อมูลแก่หน่วยงานราชการ หรือการปฏิบัติตามคำสั่งศาล',
  'terms.sharing_anonymous': 'การแชร์ข้อมูลที่ไม่สามารถระบุตัวตน:',
  'terms.sharing_anonymous_desc': 'เช่น ข้อมูลทางสถิติที่ไม่ระบุตัวตนหรือข้อมูลที่ใช้ในการวิเคราะห์เพื่อพัฒนาแอป',
  
  // Job Detail Page
  'jobDetail.error': 'เกิดข้อผิดพลาด',
  'jobDetail.errorLoadDesc': 'ไม่สามารถโหลดข้อมูลงานได้',
  'jobDetail.notFound': 'ไม่พบข้อมูลงานนี้',
  'jobDetail.invalidType': 'ประเภทงานไม่ถูกต้อง',
  'jobDetail.domestic': 'ขนส่งภายในประเทศ',
  'jobDetail.international': 'ขนส่งภายนอกประเทศ',
  'jobDetail.inbound': 'ขาเข้า',
  'jobDetail.outbound': 'ขาออก',
  'jobDetail.reportProblem': 'แจ้งปัญหา',
  'jobDetail.booking': 'Booking',
  'jobDetail.employer': 'ผู้จ้าง',
  'jobDetail.pickupPoint': 'จุดรับสินค้า',
  'jobDetail.deliveryPoint': 'จุดส่งสินค้า',
  'jobDetail.sopSuccess': 'SOP สำเร็จ',
  'jobDetail.waitingSop': 'รอ SOP',
  'jobDetail.waitingCheckIn': 'รอเช็คอิน',
  'jobDetail.podSuccess': 'POD สำเร็จ',
  'jobDetail.waitingPod': 'รอ POD',
  'jobDetail.contactPerson': 'ชื่อผู้ติดต่อ',
  'jobDetail.position': 'ตำแหน่ง',
  'jobDetail.goodsType': 'ประเภทสินค้า',
  'jobDetail.pickupTime': 'เข้ารับสินค้า',
  'jobDetail.deliveryTime': 'ส่งสินค้า',
  'jobDetail.remarks': 'หมายเหตุ',
  'jobDetail.call': 'โทร',
  'jobDetail.route': 'เส้นทาง',
  'jobDetail.viewInfo': 'ดูข้อมูล',
  'jobDetail.updateStatus': 'อัปเดตสถานะ',
  'jobDetail.startJob': 'เริ่มงาน',
  'jobDetail.startJobNow': 'เริ่มงานเลย',
  'jobDetail.pickupDeliveryPoints': 'จุดรับ/ส่ง',
  'jobDetail.errorStartJob': 'ไม่สามารถเริ่มงานได้',
  'jobDetail.startJobSuccess': 'เริ่มงานสำเร็จ',
  'jobDetail.startJobSuccessDesc': 'คุณสามารถทำงานส่งของได้แล้ว',
  'jobDetail.containerCheckpoint': 'จุดรับตู้เปล่า',
  'jobDetail.containerSuccess': 'รับตู้เปล่าสำเร็จ',
  'jobDetail.waitingContainer': 'รอรับตู้เปล่า',
  'jobDetail.startDateTime': 'วัน/เวลาเริ่มต้น',
  'jobDetail.emptyContainerDate': 'วันรับเข้าช่างต้นต้น',
  'jobDetail.receiver': 'ผู้รับสินค้า',
  'jobDetail.containerDate': 'วันคนเทนเนอร์',
  'jobDetail.containerNumber': 'เลขตู้คอนเทนเนอร์',
  'jobDetail.sealNumber': 'เลขซีล',
  'jobDetail.loadingPoint': 'จุดรับสินค้า',
  'jobDetail.unloadingPoint': 'จุดส่งสินค้า',
  'jobDetail.billOfLading': 'เลขที่เอียด',
  'jobDetail.contactPoint': 'ชื่อจุดติดต่อ',
  'jobDetail.routeCode': 'เลขทาง',
  'jobDetail.deliveryRoute': 'เส้นทาง',
  'jobDetail.emptyReturn': 'จุดคืนตู้เปล่า',
  'jobDetail.fullReturn': 'จุดคืนตู้เต็ม',
  'jobDetail.returnDeadline': 'วันที่หมดคืนตู้เปล่า',
  'jobDetail.guarantor': 'ผู้รับรอง',
  'jobDetail.returnDate': 'วันคืนตู้คอนเทนเนอร์',
  'jobDetail.startJobDesc': 'คุณสามารถเริ่มตรวจตู้เปล่าได้แล้ว',

  // Chat Page
  'chat.title': 'แชท',
  'chat.search': 'ค้นหาข้อความ',
  'chat.company': 'บริษัท',
  'chat.friends': 'เพื่อน',
  'chat.groups': 'กลุ่ม',
  'chat.online': 'ออนไลน์',
  'chat.offline': 'ออฟไลน์',
  'chat.typeMessage': 'พิมพ์ข้อความ',
  'chat.welcomeGroup': 'ยินดีต้อนรับกลุ่มสนทนา กับเพื่อนของคุณ!',
  'chat.addMembers': 'เพิ่มสมาชิก',
  'chat.memberList': 'รายชื่อสมาชิก',
  'chat.filesMedia': 'ไฟล์ รูปและวีดีโอ',
  'chat.muteNotifications': 'เปิดการแจ้งเตือน',
  'chat.deleteConversation': 'ลบการสนทนา',
  'chat.error': 'เกิดข้อผิดพลาด',
  'chat.sendError': 'ไม่สามารถส่งข้อความได้',
  'chat.muted': 'ปิดเสียงแล้ว',
  'chat.mutedDesc': 'คุณจะไม่ได้รับการแจ้งเตือนจากการสนทนานี้',
  'chat.createGroup': 'สร้างกลุ่มใหม่',
  'chat.groupName': 'ชื่อกลุ่ม',
  'chat.groupNamePlaceholder': 'ใส่ชื่อกลุ่ม',
  'chat.groupNameRequired': 'กรุณาใส่ชื่อกลุ่ม',
  'chat.selectMembers': 'เลือกสมาชิก',
  'chat.searchMembers': 'ค้นหาสมาชิก...',
  'chat.selectMembersRequired': 'กรุณาเลือกสมาชิกอย่างน้อย 1 คน',
  'chat.selectedCount': 'เลือกแล้ว',
  'chat.cancel': 'ยกเลิก',
  'chat.create': 'สร้าง',
  'chat.creating': 'กำลังสร้าง...',
  'chat.success': 'สำเร็จ',
  'chat.groupCreated': '🎉 สร้างกลุ่มแล้ว',
  'chat.groupCreatedSuccess': 'สร้างกลุ่มสำเร็จ',
  'chat.groupCreatedError': 'ไม่สามารถสร้างกลุ่มได้',
  'chat.noMembersFound': 'ไม่พบสมาชิก',
  'chat.manageGroup': 'จัดการกลุ่ม',
  'chat.info': 'ข้อมูล',
  'chat.members': 'สมาชิก',
  'chat.you': 'คุณ',
  'chat.groupNameUpdated': 'อัปเดตชื่อกลุ่มแล้ว',
  'chat.updateError': 'ไม่สามารถอัปเดตได้',
  'chat.membersAdded': 'เพิ่มสมาชิกแล้ว',
  'chat.addMembersError': 'ไม่สามารถเพิ่มสมาชิกได้',
  'chat.memberRemoved': 'ลบสมาชิกแล้ว',
  'chat.removeMemberError': 'ไม่สามารถลบสมาชิกได้',
  'chat.cannotRemoveSelf': 'ไม่สามารถลบตัวเองออกจากกลุ่มได้',
  'chat.adding': 'กำลังเพิ่ม...',
  'chat.addSelected': 'เพิ่มที่เลือก',

  // Report Problem Drawer
  'reportProblem.title': 'แจ้งปัญหา',
  'reportProblem.problemAccident': 'แจ้งปัญหา/ อุบัติเหตุ',
  'reportProblem.partialDelivery': 'ส่งมอบสินค้าบางส่วน',
  'reportProblem.pauseWork': 'หยุดงานชั่วคราว',
  'reportProblem.reportIssue': 'แจ้งปัญหา',
  'reportProblem.specifyTime': 'ระบุเวลากล่อง',
  'reportProblem.specifyReason': 'ระบุสาเหตุ',
  'reportProblem.reasonPlaceholder': 'ระบุเหตุผล',
  'reportProblem.uploadPhoto': 'อัพโหลดรูปสินค้า',
  'reportProblem.clickToTake': 'กดเพื่อถ่ายหรือเลือก',
  'reportProblem.productPhoto': 'รูปสินค้า',
  'reportProblem.fileSelected': 'เลือกไฟล์',
  'reportProblem.downloadVehicleChange': 'ดาวน์โหลดใบเปลี่ยนรถ',
  'reportProblem.confirm': 'ยืนยัน',
  'reportProblem.fillAllFields': 'กรุณากรอกข้อมูลให้ครบถ้วน',
  
  // Pickup Detail Page  
  'pickup.title': 'จุดรับสินค้า',
  'pickup.contactName': 'ชื่อผู้ติดต่อ',
  'pickup.routeNumber': 'เลขทาง',
  'pickup.address': 'ที่อยู่',
  'pickup.map': 'แผนที่',
  'pickup.productType': 'ประเภทสินค้า',
  'pickup.pickupTime': 'เข้ารับสินค้า',
  'pickup.note': 'หมายเหตุ',
  'pickup.call': 'โทร',
  'pickup.route': 'เส้นทาง',
  'pickup.checkIn': 'เช็คอิน',
  'pickup.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'pickup.confirmMessage': 'คุณต้องการเช็คอินที่ "จุดรับสินค้า Factory1" ใช่หรือไม่?',
  'pickup.cancel': 'ยกเลิก',
  'pickup.confirmButton': 'ยืนยัน',
  'pickup.checkInSuccess': 'เช็คอินสำเร็จ',
  'pickup.checkInSuccessMessage': 'คุณได้เช็คอินที่จุดรับสินค้าเรียบร้อยแล้ว',
  'pickup.error': 'เกิดข้อผิดพลาด',
  'pickup.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  'pickup.checkInError': 'ไม่สามารถบันทึกการเช็คอินได้',
  
  // Delivery Detail Page
  'delivery.title': 'จุดส่ง',
  'delivery.checkInSuccess': 'เช็คอินสำเร็จ',
  'delivery.paymentSuccess': 'ชำระเงินสำเร็จ',
  'delivery.paymentInfo': 'ข้อมูลการชำระเงิน',
  'delivery.paymentMethod': 'วิธีการชำระเงิน',
  'delivery.amount': 'จำนวนเงิน (บาท)',
  'delivery.cash': 'เงินสด',
  'delivery.mobileBanking': 'ชำระเงินผ่าน Mobile Banking',
  'delivery.qrCode': 'ชำระเงินผ่าน QR Code',
  'delivery.uploadDocument': 'อัพโหลดเอกสาร (ใบขนส่ง)',
  'delivery.clickToTake': 'กดเพื่อถ่ายหรือเลือก',
  'delivery.waybill': 'เอกสาร (ใบขนส่ง)',
  'delivery.podSuccess': 'POD สำเร็จ',
  'delivery.contactName': 'ชื่อผู้ติดต่อ',
  'delivery.routeNumber': 'เลขทาง',
  'delivery.address': 'ที่อยู่',
  'delivery.deliveryTime': 'เข้ารับสินค้า',
  'delivery.productType': 'ประเภทสินค้า',
  'delivery.note': 'หมายเหตุ',
  'delivery.call': 'โทร',
  'delivery.route': 'เส้นทาง',
  'delivery.checkIn': 'เช็คอิน',
  'delivery.payment': 'ชำระเงิน',
  'delivery.selectPaymentMethod': 'เลือกวิธีการชำระเงิน',
  'delivery.confirmPayment': 'ยืนยันการชำระเงิน',
  'delivery.confirmPaymentMessage': 'คุณต้องการยืนยันการชำระเงินใช่หรือไม่?',
  'delivery.paymentSuccessToast': 'บันทึกข้อมูลการชำระเงินเรียบร้อยแล้ว',
  'delivery.paymentError': 'ไม่สามารถบันทึกการชำระเงินได้',
  'delivery.podError': 'ไม่สามารถยืนยัน POD ได้',
  'delivery.podSuccessToast': 'บันทึกข้อมูล POD เรียบร้อยแล้ว',
  'delivery.uploadError': 'ไม่สามารถอัปโหลดเอกสารได้',
  'delivery.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'delivery.confirmMessage': 'คุณต้องการเช็คอินที่ "จุดส่ง หวค.ชัยน้ำตาล" ใช่หรือไม่?',
  'delivery.cancel': 'ยกเลิก',
  'delivery.confirmButton': 'ยืนยัน',
  
  // Container Check-in Page
  'container.title': 'จุดรับตู้เปล่า',
  'container.viewExpenses': 'ดูค่าใช้จ่าย',
  'container.addExpenses': 'เพิ่มค่าใช้จ่าย',
  'container.reportProblem': 'แจ้งปัญหา',
  'container.emptyContainerPoint': 'จุดรับตู้เปล่า',
  'container.startTime': 'วัน/เวลาเริ่มต้น',
  'container.checkpoint': 'วันรับเข้าช่างต้นต้น',
  'container.firstDatePickup': 'วันรับเข้าช่างต้นต้น (FIRST DATE PICK UP CTNR)',
  'container.pair': 'คู่ที่',
  'container.containerNo': 'เลขตู้คอนเทนเนอร์ (Container No.)',
  'container.sealNo': 'เลขซีล (Seal No.)',
  'container.route': 'เส้นทาง',
  'container.checkIn': 'เช็คอิน',
  'container.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'container.confirmMessage1': 'คุณต้องการเช็คอินที่',
  'container.confirmMessage2': 'ใช่หรือไม่?',
  'container.cancel': 'ยกเลิก',
  'container.confirm': 'ยืนยัน',
  'container.checkInSuccess': 'เช็คอินสำเร็จ',
  'container.checkInSuccessMessage': 'สถานะเปลี่ยนเป็น รอรับตู้เปล่า แล้ว',
  'container.checkInError': 'ไม่สามารถเช็คอินได้',
  'container.error': 'เกิดข้อผิดพลาด',
  'container.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  
  // SOP Check-in Page
  'sop.title': 'จุดรับสินค้า',
  'sop.checkInSuccess': 'เช็คอินสำเร็จ',
  'sop.uploadPhoto': 'อัพโหลดรูปสินค้า',
  'sop.clickToTake': 'กดเพื่อถ่ายหรือเลือก',
  'sop.productPhoto': 'รูปสินค้า',
  'sop.confirmSOP': 'ยืนยัน SOP',
  'sop.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'sop.confirmMessage': 'คุณต้องการยืนยันการยืนยันสินค้าด้วยไฟล์สแกน Scan of Package (SOP) ใช่หรือไม่?',
  'sop.cancel': 'ยกเลิก',
  'sop.confirm': 'ยืนยัน',
  'sop.saving': 'กำลังบันทึก...',
  'sop.photoRequired': 'กรุณาอัปโหลดรูปภาพ',
  'sop.photoRequiredMessage': 'คุณต้องอัปโหลดรูปสินค้าก่อนยืนยัน SOP',
  'sop.sopSuccess': 'ยืนยัน SOP สำเร็จ',
  'sop.sopSuccessMessage': 'บันทึกข้อมูลเรียบร้อยแล้ว',
  'sop.error': 'เกิดข้อผิดพลาด',
  'sop.errorMessage': 'ไม่สามารถบันทึกข้อมูลได้ กรุณาลองใหม่อีกครั้ง',
  'sop.selectSource': 'เลือกแหล่งที่มาของรูปภาพ',
  'sop.takePhoto': 'ถ่ายภาพ',
  'sop.selectFromGallery': 'เลือกรูปจากแกลอรี่',
  
  // Container SOP Page
  'containerSop.title': 'จุดรับตู้เปล่า',
  'containerSop.uploadPhoto': 'อัพโหลดรูปตู้เปล่า',
  'containerSop.clickToTake': 'คลิกเพื่อถ่ายหรือเลือกรูปตู้เปล่า',
  'containerSop.confirmButton': 'ยืนยันรับตู้เปล่า',
  'containerSop.confirmTitle': 'ยืนยันการรับตู้เปล่า',
  'containerSop.confirmMessage': 'คุณต้องการยืนยันการรับตู้เปล่าใช่หรือไม่?',
  'containerSop.photoRequiredMessage': 'กรุณาอัพโหลดรูปภาพตู้เปล่า',
  'containerSop.success': 'สำเร็จ',
  'containerSop.successMessage': 'บันทึกข้อมูลสำเร็จ',
  'containerSop.saveError': 'ไม่สามารถบันทึกข้อมูลได้',
  'containerSop.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  'containerSop.noData': 'ไม่พบข้อมูลงาน',
  'containerSop.loading': 'กำลังโหลด...',
};

// English translations
const enTranslations: Record<string, string> = {
  // Settings Page
  'settings.title': 'Settings',
  'settings.profile': 'Profile',
  'settings.personal_info': 'Personal Information',
  'settings.account': 'Account',
  'settings.vehicle_info': 'Vehicle Information',
  'settings.general': 'General',
  'settings.notifications': 'Notifications',
  'settings.notifications_enabled': 'Notifications On',
  'settings.notifications_disabled': 'Notifications Off',
  'settings.about': 'About App',
  'settings.language': 'Language',
  'settings.terms': 'Terms of Service and Policy',
  'settings.contact': 'Contact Center',
  'settings.sign_out': 'Sign Out',
  'settings.sign_out_confirm': 'Do you want to sign out?',
  'settings.sign_out_description': 'Signing out will require you to log in again next time. Please confirm sign out.',
  'settings.cancel': 'Cancel',
  
  // Language Page
  'language.title': 'Language',
  'language.thai': 'ภาษาไทย',
  'language.english': 'English',
  
  // Bottom Navigation
  'nav.home': 'Home',
  'nav.dashboard': 'Dashboard',
  'nav.chat': 'Chat',
  'nav.settings': 'Settings',
  
  // Home Page
  'home.search': 'Search',
  'home.recommended': 'Recommended Jobs for You',
  'home.items': 'items',
  'home.error_load': 'Error',
  'home.error_load_desc': 'Unable to load jobs',
  'home.error_accept': 'Unable to accept job',
  'home.accept_success': 'Job Accepted',
  'home.accept_success_desc': 'You have accepted job',
  'home.greeting': '👋',
  'home.sunday': 'Sunday',
  'home.monday': 'Monday',
  'home.tuesday': 'Tuesday',
  'home.wednesday': 'Wednesday',
  'home.thursday': 'Thursday',
  'home.friday': 'Friday',
  'home.saturday': 'Saturday',
  'home.current_jobs': 'Current Jobs',
  'home.bidding': 'Bidding',
  'home.income': 'Income',
  'home.job_history': 'Job History',
  'home.sign_out_confirm': 'Do you want to sign out?',
  'home.sign_out_desc': 'Signing out will require you to log in again next time. Please confirm sign out.',
  'home.sign_out_btn': 'Sign Out',
  'home.cancel': 'Cancel',
  
  // Job Card
  'job.order_code': 'Order Code',
  'job.employer': 'Employer',
  'job.domestic': 'Domestic Transport',
  'job.international': 'International Transport',
  'job.inbound': 'Inbound',
  'job.outbound': 'Outbound',
  'job.origin': 'Origin',
  'job.destination': 'Destination',
  'job.equipment': 'Vehicle Equipment',
  'job.safety': 'Safety Equipment',
  'job.accept': 'Accept Job',
  'job.accepted': 'Job Accepted',
  
  // Confirm Job Dialog
  'confirm.title': 'Confirm Job Acceptance',
  'confirm.order_code': 'Order Code',
  'confirm.employer': 'Employer',
  'confirm.message': 'If you want to accept this job, please "Confirm"',
  'confirm.cancel': 'Cancel',
  'confirm.confirm': 'Confirm',
  
  // Job History Page
  'jobHistory.title': 'Job History',
  'jobHistory.all': 'All',
  'jobHistory.inProgress': 'In Progress',
  'jobHistory.completed': 'Completed',
  'jobHistory.selectMonth': 'Select Month',
  'jobHistory.allMonths': 'All Months',
  'jobHistory.january': 'January',
  'jobHistory.february': 'February',
  'jobHistory.march': 'March',
  'jobHistory.april': 'April',
  'jobHistory.may': 'May',
  'jobHistory.june': 'June',
  'jobHistory.july': 'July',
  'jobHistory.august': 'August',
  'jobHistory.september': 'September',
  'jobHistory.october': 'October',
  'jobHistory.november': 'November',
  'jobHistory.december': 'December',
  'jobHistory.loading': 'Loading...',
  'jobHistory.noData': 'No job history found',
  'jobHistory.statusCompleted': 'Completed',
  'jobHistory.statusDelivering': 'In Delivery',
  'jobHistory.statusAccepted': 'Accepted',
  
  // Current Jobs Page
  'currentJobs.title': 'Current Jobs',
  'currentJobs.search': 'Search by name, order, order code',
  'currentJobs.empty': 'No jobs available at the moment',
  'currentJobs.viewDetails': 'View Job Details',
  'currentJobs.filter': 'Filter',
  'currentJobs.dateRange': 'Job Assignment Date',
  'currentJobs.startDate': 'Start Date',
  'currentJobs.endDate': 'End Date',
  'currentJobs.clearFilter': 'Clear',
  'currentJobs.applyFilter': 'Search',
  'currentJobs.startJobDate': 'Start Date',
  'currentJobs.errorLoad': 'Error',
  'currentJobs.errorLoadDesc': 'Unable to load jobs',
  
  // Bidding Page
  'bidding.title': 'Bidding',
  'bidding.biddingTab': 'Bidding',
  'bidding.historyTab': 'History',
  'bidding.noJobs': 'No jobs available for bidding',
  'bidding.placeBid': 'Place Bid',
  'bidding.noHistory': 'No bidding history yet',
  'bidding.bidAt': 'Bid placed at',
  'bidding.statusPending': 'Pending',
  'bidding.statusAccepted': 'Completed',
  'bidding.statusRejected': 'Rejected',
  'bidding.monthLabel': 'February',
  
  // Income Page
  'income.title': 'My Income',
  'income.all': 'All',
  'income.paid': 'Paid',
  'income.unpaid': 'Unpaid',
  'income.selectMonth': 'Select Month',
  'income.viewDetails': 'View Job Details',
  'income.noData': 'No income data',
  'income.noPaid': 'No paid jobs',
  'income.noUnpaid': 'No unpaid jobs',
  'income.errorLoad': 'Error',
  'income.errorLoadDesc': 'Unable to load income data',
  
  // Dashboard Page
  'dashboard.finance': 'Finance (Expenses)',
  'dashboard.finance_desc': 'Track income and expenses easily',
  'dashboard.shipping': 'Shipping',
  'dashboard.shipping_desc': 'Check your shipments',
  'dashboard.customer': 'Customer',
  'dashboard.customer_desc': 'View your customer information',
  'dashboard.product': 'Product',
  'dashboard.product_desc': 'View product type information',
  'dashboard.view': 'View',

  // Finance Page
  'finance.title': 'Finance',
  'finance.day': 'Day',
  'finance.month': 'Month',
  'finance.year': 'Year',
  'finance.profit': 'Profit',
  'finance.expenses': 'Expenses',
  'finance.total_income': 'Total Income',
  'finance.compare_year': 'Compared to year: 2023',
  'finance.buddhist_era': 'Year',
  'finance.income': 'Income',
  'finance.pending_payments': 'Pending Payments',
  'finance.companies': 'Companies',

  // Shipping Page
  'shipping.title': 'Shipping',
  'shipping.all_types': 'All Transport Types',
  'shipping.tractor': 'Tractor',
  'shipping.12wheels': '12 Wheels',
  'shipping.10wheels': '10 Wheels',
  'shipping.6wheels': '6 Wheels',
  'shipping.4wheels': '4 Wheels',
  'shipping.job_data': 'Shipping Jobs Data',
  'shipping.all_jobs': 'All Jobs',
  'shipping.success': 'Success',
  'shipping.in_delivery': 'In Delivery',
  'shipping.cancelled': 'Cancelled',
  'shipping.by_region': 'Shipping by Region',
  'shipping.north': 'North',
  'shipping.central': 'Central',
  'shipping.northeast': 'Northeast',
  'shipping.east': 'East',
  'shipping.west': 'West',
  'shipping.south': 'South',

  // Customer Page
  'customer.title': 'Customer',
  'customer.top_5': 'Top 5',
  'customer.jobs': 'jobs',

  // Product Page
  'product.title': 'Product',
  'product.product_types': 'Product Types',
  'product.top_5': 'Top 5',
  'product.jobs': 'jobs',
  
  // Search Page
  'search.title': 'Search',
  'search.search': 'Search',
  'search.results': 'Search Results',
  'search.no_results': 'No results found',
  'search.recent': 'Recent Searches',
  'search.popular': 'Popular Searches',
  'search.filter': 'Filter',
  'search.filter_desc': 'Filter search results',
  'search.domestic': 'Domestic Transport',
  'search.international': 'International Transport',
  'search.province': 'Province',
  'search.district': 'District',
  'search.select_province': 'Select Province',
  'search.select_district': 'Select District',
  'search.select_district_first': 'Please select province first',
  'search.price_range': 'Price Range (฿)',
  'search.min_price': 'Enter minimum price',
  'search.max_price': 'Enter maximum price',
  'search.clear': 'Clear',
  'search.apply': 'Search',
  
  // Profile Page
  'profile.title': 'Profile',
  'profile.first_name': 'First Name',
  'profile.last_name': 'Last Name',
  'profile.phone': 'Phone Number',
  'profile.email': 'Email',
  'profile.work_areas': 'Districts or provinces you work regularly',
  'profile.price_range': 'Job Price Range (฿)',
  'profile.change_avatar': 'Confirm Profile Picture Change',
  'profile.change_avatar_desc': 'Do you want to change your profile picture to this one?',
  'profile.confirm': 'Confirm',
  'profile.cancel': 'Cancel',
  'profile.uploading': 'Uploading...',
  'profile.error_upload': 'Unable to upload image',
  'profile.error_update': 'Unable to update profile',
  'profile.success': 'Success',
  'profile.success_desc': 'Profile picture updated',
  
  // Account Page
  'account.title': 'Account',
  'account.username': 'Username',
  'account.no_data': 'No data',
  'account.password': 'Password',
  'account.delete': 'Delete Account',
  'account.delete_confirm': 'Are you sure you want to delete your account?',
  'account.delete_desc': 'Deleting this account will remove all data',
  'account.delete_personal': 'Personal information',
  'account.delete_history': 'Service history',
  'account.delete_transactions': 'All transaction data',
  'account.delete_warning': 'Account deletion cannot be undone',
  'account.deleting': 'Deleting...',
  'account.cancel': 'Cancel',
  'account.delete_success': 'Account Deleted Successfully',
  'account.delete_success_desc': 'Your account has been deleted',
  'account.delete_error': 'Error',
  'account.delete_error_desc': 'Unable to delete account. Please try again.',
  
  // Terms Page
  'terms.title': 'Terms of Service and Policy',
  'terms.heading': 'Truckers  Privacy Policy for Drivers',
  'terms.updated_date': 'Effective as of January 15, 2024',
  'terms.collection_title': 'Data We Collect',
  'terms.collection_intro': 'We collect information necessary to provide the Truckers app services to drivers. This includes information you provide directly and information we collect from your use of the app, such as:',
  'terms.personal_data': 'Personal Data:',
  'terms.personal_data_desc': 'Such as name, email, phone number, and account information related to transportation',
  'terms.technical_data': 'Technical Data:',
  'terms.technical_data_desc': 'Including trip data, location (GPS), speed, route selection, start and end times of transportation',
  'terms.price_data': 'Price Data:',
  'terms.price_data_desc': 'Including vehicle registration number, vehicle type, and information related to truck condition',
  'terms.financial_data': 'Financial Data:',
  'terms.financial_data_desc': 'Data used for payment such as bank account details or credit card information',
  'terms.communication_data': 'Communication Data:',
  'terms.communication_data_desc': 'Messages, conversations, or communications through the app related to service provision',
  'terms.usage_title': 'How We Use Data',
  'terms.usage_intro': 'We will use your data in various ways, such as:',
  'terms.usage_1': 'Processing transportation request submissions',
  'terms.usage_2': 'Calculating service fees and payment',
  'terms.usage_3': 'Improving service provision and app development',
  'terms.usage_4': 'Contacting you to provide information about transportation status or notifications',
  'terms.usage_5': 'Improving your user experience',
  'terms.usage_6': 'Complying with legal requirements',
  'terms.sharing_title': 'Data Sharing',
  
  // Job Detail Page
  'jobDetail.error': 'Error',
  'jobDetail.errorLoadDesc': 'Unable to load job data',
  'jobDetail.notFound': 'Job not found',
  'jobDetail.invalidType': 'Invalid job type',
  'jobDetail.domestic': 'Domestic Transport',
  'jobDetail.international': 'International Transport',
  'jobDetail.inbound': 'Inbound',
  'jobDetail.outbound': 'Outbound',
  'jobDetail.reportProblem': 'Report Problem',
  'jobDetail.booking': 'Booking',
  'jobDetail.employer': 'Employer',
  'jobDetail.pickupPoint': 'Pickup Point',
  'jobDetail.deliveryPoint': 'Delivery Point',
  'jobDetail.sopSuccess': 'SOP Complete',
  'jobDetail.waitingSop': 'Waiting SOP',
  'jobDetail.waitingCheckIn': 'Waiting Check-in',
  'jobDetail.podSuccess': 'POD Complete',
  'jobDetail.waitingPod': 'Waiting POD',
  'jobDetail.contactPerson': 'Contact Person',
  'jobDetail.position': 'Position',
  'jobDetail.goodsType': 'Goods Type',
  'jobDetail.pickupTime': 'Pickup Time',
  'jobDetail.deliveryTime': 'Delivery Time',
  'jobDetail.remarks': 'Remarks',
  'jobDetail.call': 'Call',
  'jobDetail.route': 'Route',
  'jobDetail.viewInfo': 'View Info',
  'jobDetail.updateStatus': 'Update Status',
  'jobDetail.startJob': 'Start Job',
  'jobDetail.startJobNow': 'Start Job Now',
  'jobDetail.pickupDeliveryPoints': 'Pickup/Delivery Points',
  'jobDetail.errorStartJob': 'Unable to start job',
  'jobDetail.startJobSuccess': 'Job Started Successfully',
  'jobDetail.startJobSuccessDesc': 'You can now proceed with delivery',
  'jobDetail.containerCheckpoint': 'Empty Container Pickup',
  'jobDetail.containerSuccess': 'Container Pickup Complete',
  'jobDetail.waitingContainer': 'Waiting Container',
  'jobDetail.startDateTime': 'Start Date/Time',
  'jobDetail.emptyContainerDate': 'Empty Container Date',
  'jobDetail.receiver': 'Receiver',
  'jobDetail.containerDate': 'Container Date',
  'jobDetail.containerNumber': 'Container Number',
  'jobDetail.sealNumber': 'Seal Number',
  'jobDetail.loadingPoint': 'Loading Point',
  'jobDetail.unloadingPoint': 'Unloading Point',
  'jobDetail.billOfLading': 'Bill of Lading',
  'jobDetail.contactPoint': 'Contact Point',
  'jobDetail.routeCode': 'Route Code',
  'jobDetail.deliveryRoute': 'Route',
  'jobDetail.emptyReturn': 'Empty Return Point',
  'jobDetail.fullReturn': 'Full Return Point',
  'jobDetail.returnDeadline': 'Return Deadline',
  'jobDetail.guarantor': 'Guarantor',
  'jobDetail.returnDate': 'Return Date',
  'jobDetail.startJobDesc': 'You can now start container inspection',
  'terms.sharing_intro': 'We will not share your personal data with third parties, except in the following cases:',
  'terms.sharing_provider': 'Service Providers We Hire:',
  'terms.sharing_provider_desc': 'Companies or individuals we use for services in various areas (such as payment services, data analysis) that have privacy terms to protect your data',
  'terms.sharing_legal': 'Legal Compliance:',
  'terms.sharing_legal_desc': 'In cases where we are required by law, such as providing information to government agencies or complying with court orders',
  'terms.sharing_anonymous': 'Sharing of De-identified Data:',
  'terms.sharing_anonymous_desc': 'Such as anonymized statistical data or data used for analysis to improve the app',
  
  // Chat Page
  'chat.title': 'Chat',
  'chat.search': 'Search conversations',
  'chat.company': 'Company',
  'chat.friends': 'Friends',
  'chat.groups': 'Groups',
  'chat.online': 'Online',
  'chat.offline': 'Offline',
  'chat.typeMessage': 'Type a message',
  'chat.welcomeGroup': 'Welcome to the group chat with your friends!',
  'chat.addMembers': 'Add Members',
  'chat.memberList': 'Member List',
  'chat.filesMedia': 'Files and Media',
  'chat.muteNotifications': 'Mute Notifications',
  'chat.deleteConversation': 'Delete Conversation',
  'chat.error': 'Error',
  'chat.sendError': 'Failed to send message',
  'chat.muted': 'Muted',
  'chat.mutedDesc': 'You will no longer receive notifications from this conversation',
  'chat.createGroup': 'Create New Group',
  'chat.groupName': 'Group Name',
  'chat.groupNamePlaceholder': 'Enter group name',
  'chat.groupNameRequired': 'Please enter group name',
  'chat.selectMembers': 'Select Members',
  'chat.searchMembers': 'Search members...',
  'chat.selectMembersRequired': 'Please select at least 1 member',
  'chat.selectedCount': 'Selected',
  'chat.cancel': 'Cancel',
  'chat.create': 'Create',
  'chat.creating': 'Creating...',
  'chat.success': 'Success',
  'chat.groupCreated': '🎉 Group created',
  'chat.groupCreatedSuccess': 'Group created successfully',
  'chat.groupCreatedError': 'Failed to create group',
  'chat.noMembersFound': 'No members found',
  'chat.manageGroup': 'Manage Group',
  'chat.info': 'Info',
  'chat.members': 'Members',
  'chat.you': 'You',
  'chat.groupNameUpdated': 'Group name updated',
  'chat.updateError': 'Failed to update',
  'chat.membersAdded': 'Members added',
  'chat.addMembersError': 'Failed to add members',
  'chat.memberRemoved': 'Member removed',
  'chat.removeMemberError': 'Failed to remove member',
  'chat.cannotRemoveSelf': 'Cannot remove yourself from group',
  'chat.adding': 'Adding...',
  'chat.addSelected': 'Add Selected',

  // Report Problem Drawer
  'reportProblem.title': 'Report Problem',
  'reportProblem.problemAccident': 'Report Problem / Accident',
  'reportProblem.partialDelivery': 'Partial Delivery',
  'reportProblem.pauseWork': 'Pause Work',
  'reportProblem.reportIssue': 'Report Issue',
  'reportProblem.specifyTime': 'Specify Time',
  'reportProblem.specifyReason': 'Specify Reason',
  'reportProblem.reasonPlaceholder': 'Enter reason',
  'reportProblem.uploadPhoto': 'Upload Product Photo',
  'reportProblem.clickToTake': 'Click to take or select',
  'reportProblem.productPhoto': 'product photo',
  'reportProblem.fileSelected': 'File selected',
  'reportProblem.downloadVehicleChange': 'Download Vehicle Change Form',
  'reportProblem.confirm': 'Confirm',
  'reportProblem.fillAllFields': 'Please fill in all fields',
  
  // Pickup Detail Page
  'pickup.title': 'Pickup Point',
  'pickup.contactName': 'Contact Name',
  'pickup.routeNumber': 'Route Number',
  'pickup.address': 'Address',
  'pickup.map': 'Map',
  'pickup.productType': 'Product Type',
  'pickup.pickupTime': 'Pickup Time',
  'pickup.note': 'Note',
  'pickup.call': 'Call',
  'pickup.route': 'Route',
  'pickup.checkIn': 'Check In',
  'pickup.confirmTitle': 'Confirm Status',
  'pickup.confirmMessage': 'Do you want to check in at "Pickup Point Factory1"?',
  'pickup.cancel': 'Cancel',
  'pickup.confirmButton': 'Confirm',
  'pickup.checkInSuccess': 'Check-in Successful',
  'pickup.checkInSuccessMessage': 'You have checked in at the pickup point',
  'pickup.error': 'Error',
  'pickup.loadError': 'Unable to load job data',
  'pickup.checkInError': 'Unable to save check-in',
  
  // Delivery Detail Page
  'delivery.title': 'Delivery Point',
  'delivery.checkInSuccess': 'Check-in Successful',
  'delivery.paymentSuccess': 'Payment Successful',
  'delivery.paymentInfo': 'Payment Information',
  'delivery.paymentMethod': 'Payment Method',
  'delivery.amount': 'Amount (Baht)',
  'delivery.cash': 'Cash',
  'delivery.mobileBanking': 'Mobile Banking',
  'delivery.qrCode': 'QR Code',
  'delivery.uploadDocument': 'Upload Document (Waybill)',
  'delivery.clickToTake': 'Click to take or select',
  'delivery.waybill': 'document (waybill)',
  'delivery.podSuccess': 'POD Successful',
  'delivery.contactName': 'Contact Name',
  'delivery.routeNumber': 'Route Number',
  'delivery.address': 'Address',
  'delivery.deliveryTime': 'Delivery Time',
  'delivery.productType': 'Product Type',
  'delivery.note': 'Note',
  'delivery.call': 'Call',
  'delivery.route': 'Route',
  'delivery.checkIn': 'Check In',
  'delivery.payment': 'Payment',
  'delivery.selectPaymentMethod': 'Select Payment Method',
  'delivery.confirmPayment': 'Confirm Payment',
  'delivery.confirmPaymentMessage': 'Do you want to confirm the payment?',
  'delivery.paymentSuccessToast': 'Payment information saved successfully',
  'delivery.paymentError': 'Unable to save payment',
  'delivery.podError': 'Unable to confirm POD',
  'delivery.podSuccessToast': 'POD information saved successfully',
  'delivery.uploadError': 'Unable to upload document',
  'delivery.confirmTitle': 'Confirm Status',
  'delivery.confirmMessage': 'Do you want to check in at "Delivery Point Chai Sugar"?',
  'delivery.cancel': 'Cancel',
  'delivery.confirmButton': 'Confirm',
  
  // Container Check-in Page
  'container.title': 'Empty Container Point',
  'container.viewExpenses': 'View Expenses',
  'container.addExpenses': 'Add Expenses',
  'container.reportProblem': 'Report Problem',
  'container.emptyContainerPoint': 'Empty Container Point',
  'container.startTime': 'Start Date/Time',
  'container.checkpoint': 'Checkpoint',
  'container.firstDatePickup': 'First Date Pick Up CTNR',
  'container.pair': 'Pair',
  'container.containerNo': 'Container No.',
  'container.sealNo': 'Seal No.',
  'container.route': 'Route',
  'container.checkIn': 'Check In',
  'container.confirmTitle': 'Confirm Status',
  'container.confirmMessage1': 'Do you want to check in at',
  'container.confirmMessage2': '?',
  'container.cancel': 'Cancel',
  'container.confirm': 'Confirm',
  'container.checkInSuccess': 'Check-in Successful',
  'container.checkInSuccessMessage': 'Status changed to waiting for empty container',
  'container.checkInError': 'Unable to check in',
  'container.error': 'Error',
  'container.loadError': 'Unable to load job data',
  
  // SOP Check-in Page
  'sop.title': 'Pickup Point',
  'sop.checkInSuccess': 'Check-in Successful',
  'sop.uploadPhoto': 'Upload Product Photo',
  'sop.clickToTake': 'Click to take or select',
  'sop.productPhoto': 'product photo',
  'sop.confirmSOP': 'Confirm SOP',
  'sop.confirmTitle': 'Confirm Status',
  'sop.confirmMessage': 'Do you want to confirm the product with Scan of Package (SOP)?',
  'sop.cancel': 'Cancel',
  'sop.confirm': 'Confirm',
  'sop.saving': 'Saving...',
  'sop.photoRequired': 'Please upload a photo',
  'sop.photoRequiredMessage': 'You must upload a product photo before confirming SOP',
  'sop.sopSuccess': 'SOP Confirmed Successfully',
  'sop.sopSuccessMessage': 'Information saved successfully',
  'sop.error': 'Error',
  'sop.errorMessage': 'Unable to save information. Please try again',
  'sop.selectSource': 'Select Photo Source',
  'sop.takePhoto': 'Take Photo',
  'sop.selectFromGallery': 'Select from Gallery',
  
  // Container SOP Page
  'containerSop.title': 'Empty Container Point',
  'containerSop.uploadPhoto': 'Upload Empty Container Photo',
  'containerSop.clickToTake': 'Click to take or select empty container photo',
  'containerSop.confirmButton': 'Confirm Empty Container Receipt',
  'containerSop.confirmTitle': 'Confirm Empty Container Receipt',
  'containerSop.confirmMessage': 'Do you want to confirm receiving the empty container?',
  'containerSop.photoRequiredMessage': 'Please upload an empty container photo',
  'containerSop.success': 'Success',
  'containerSop.successMessage': 'Information saved successfully',
  'containerSop.saveError': 'Unable to save information',
  'containerSop.loadError': 'Unable to load job data',
  'containerSop.noData': 'Job data not found',
  'containerSop.loading': 'Loading...',
};
