import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'th';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    const translations = language === 'th' ? thTranslations : enTranslations;
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Thai translations
const thTranslations: Record<string, string> = {
  // Settings Page
  'settings.title': 'ตั้งค่า',
  'settings.profile': 'โปรไฟล์',
  'settings.personal_info': 'ข้อมูลส่วนตัว',
  'settings.account': 'บัญชี',
  'settings.vehicle_info': 'ข้อมูลรถ',
  'settings.general': 'ทั่วไป',
  'settings.notifications': 'การแจ้งเตือน',
  'settings.notifications_enabled': 'เปิดแจ้งเตือน',
  'settings.notifications_disabled': 'ปิดแจ้งเตือน',
  'settings.about': 'ข้อมูลเกี่ยวกับแอป',
  'settings.language': 'ภาษา',
  'settings.terms': 'เงื่อนไขการใช้บริการและนโยบาย',
  'settings.contact': 'ติดต่อศูนย์',
  'settings.sign_out': 'ออกจากระบบ',
  'settings.sign_out_confirm': 'คุณต้องการออกจากระบบหรือไม่?',
  'settings.sign_out_description': 'การออกจากระบบจะทำให้คุณต้องล็อกอินเข้าสู่ระบบอีกครั้ง ในครั้งถัดไป กรุณายืนยันออกจากระบบ',
  'settings.cancel': 'ยกเลิก',
  
  // Language Page
  'language.title': 'ภาษา',
  'language.thai': 'ภาษาไทย',
  'language.english': 'English',
  
  // Bottom Navigation
  'nav.home': 'หน้าแรก',
  'nav.dashboard': 'แผงควบคุม',
  'nav.chat': 'แชท',
  'nav.settings': 'ตั้งค่า',
  
  // Home Page
  'home.search': 'ค้นหา',
  'home.recommended': 'งานแนะนำสำหรับคุณ',
  'home.items': 'รายการ',
  'home.error_load': 'เกิดข้อผิดพลาด',
  'home.error_load_desc': 'ไม่สามารถโหลดข้อมูลงานได้',
  'home.error_accept': 'ไม่สามารถรับงานได้',
  'home.accept_success': 'รับงานสำเร็จ',
  'home.accept_success_desc': 'คุณได้รับงาน',
  'home.greeting': '👋',
  'home.sunday': 'วันอาทิตย์',
  'home.monday': 'วันจันทร์',
  'home.tuesday': 'วันอังคาร',
  'home.wednesday': 'วันพุธ',
  'home.thursday': 'วันพฤหัสบดี',
  'home.friday': 'วันศุกร์',
  'home.saturday': 'วันเสาร์',
  'home.current_jobs': 'งานปัจจุบัน',
  'home.bidding': 'เสนอราคา',
  'home.income': 'รายได้',
  'home.job_history': 'ประวัติงาน',
  'home.sign_out_confirm': 'คุณต้องการออกจากระบบหรือไม่?',
  'home.sign_out_desc': 'การออกจากระบบจะทำให้คุณต้องล็อกอินเข้าสู่ระบบอีกครั้ง ในครั้งถัดไป กรุณายืนยันออกจากระบบ',
  'home.sign_out_btn': 'ออกจากระบบ',
  'home.cancel': 'ยกเลิก',
  
  // Job Card
  'job.order_code': 'รหัสออเดอร์',
  'job.employer': 'ผู้จ้าง',
  'job.domestic': 'ขนส่งภายในประเทศ',
  'job.international': 'ขนส่งภายนอกประเทศ',
  'job.inbound': 'ขาเข้า',
  'job.outbound': 'ขาออก',
  'job.origin': 'ต้นทาง',
  'job.destination': 'ปลายทาง',
  'job.equipment': 'อุปกรณ์ติดรถ',
  'job.safety': 'อุปกรณ์ Safety',
  'job.accept': 'รับงานนี้',
  'job.accepted': 'รับงานนี้แล้ว',
  
  // Confirm Job Dialog
  'confirm.title': 'ยืนยันการรับงาน',
  'confirm.order_code': 'รหัสออเดอร์',
  'confirm.employer': 'ผู้จ้าง',
  'confirm.message': 'หากคุณต้องการรับรถงานที่ "ยืนยัน"',
  'confirm.cancel': 'ยกเลิก',
  'confirm.confirm': 'ยืนยัน',
  
  // Dashboard Page
  'dashboard.finance': 'การเงิน (ค่าใช้จ่าย)',
  'dashboard.finance_desc': 'ติดตามรายรับ, รายจ่าย ได้ง่าย',
  'dashboard.shipping': 'การจัดส่ง',
  'dashboard.shipping_desc': 'ตรวจสอบการจัดส่งของคุณ',
  'dashboard.customer': 'ลูกค้า',
  'dashboard.customer_desc': 'ดูข้อมูลลูกค้าของคุณ',
  'dashboard.product': 'สินค้า',
  'dashboard.product_desc': 'ดูข้อมูลประเภทสินค้า',
  'dashboard.view': 'ดู',
  
  // Search Page
  'search.title': 'ค้นหา',
  'search.search': 'ค้นหา',
  'search.results': 'ผลการค้นหา',
  'search.no_results': 'ไม่พบผลการค้นหา',
  'search.recent': 'คำค้นหาล่าสุด',
  'search.popular': 'คำค้นหายอดนิยม',
  'search.filter': 'ตัวกรอง',
  'search.filter_desc': 'กรองผลการค้นหา',
  'search.domestic': 'ขนส่งภายในประเทศ',
  'search.international': 'ขนส่งภายนอกประเทศ',
  'search.province': 'จังหวัด',
  'search.district': 'อำเภอ',
  'search.select_province': 'เลือกจังหวัด',
  'search.select_district': 'เลือกอำเภอ',
  'search.select_district_first': 'กรุณาเลือกจังหวัดก่อน',
  'search.price_range': 'ช่วงราคา (฿)',
  'search.min_price': 'ใส่ราคาต่ำสุด',
  'search.max_price': 'ใส่ราคาสูงสุด',
  'search.clear': 'ล้างค่า',
  'search.apply': 'ค้นหา',
  
  // Profile Page
  'profile.title': 'โปรไฟล์',
  'profile.first_name': 'ชื่อ',
  'profile.last_name': 'นามสกุล',
  'profile.phone': 'เบอร์โทรศัพท์',
  'profile.email': 'อีเมล',
  'profile.work_areas': 'อำเภอ หรือ จังหวัด ที่ถนัดหรือจังหวัดทั่วเป็นประจำ',
  'profile.price_range': 'เรทราคาวังงาน (฿)',
  'profile.change_avatar': 'ยืนยันการเปลี่ยนรูปโปรไฟล์',
  'profile.change_avatar_desc': 'คุณต้องการเปลี่ยนรูปโปรไฟล์เป็นรูปนี้หรือไม่?',
  'profile.confirm': 'ยืนยัน',
  'profile.cancel': 'ยกเลิก',
  'profile.uploading': 'กำลังอัพโหลด...',
  'profile.error_upload': 'ไม่สามารถอัพโหลดรูปภาพได้',
  'profile.error_update': 'ไม่สามารถอัพเดทโปรไฟล์ได้',
  'profile.success': 'สำเร็จ',
  'profile.success_desc': 'อัพเดทรูปโปรไฟล์แล้ว',
  
  // Account Page
  'account.title': 'บัญชี',
  'account.username': 'ชื่อผู้ใช้',
  'account.no_data': 'ไม่มีข้อมูล',
  'account.password': 'รหัสผ่าน',
  'account.delete': 'ลบบัญชี',
  'account.delete_confirm': 'คุณกำลังจะลบบัญชีใช่ไหม',
  'account.delete_desc': 'การลบบัญชีนี้จะเป็นการลบข้อมูลทั้งหมด',
  'account.delete_personal': 'ข้อมูลส่วนตัว',
  'account.delete_history': 'ประวัติการใช้บริการ',
  'account.delete_transactions': 'ข้อมูลธุรกรรมทั้งหมด',
  'account.delete_warning': 'หลังจากลบบัญชีแล้วจะไม่สามารถกู้คืนได้',
  'account.deleting': 'กำลังลบ...',
  'account.cancel': 'ยกเลิก',
  'account.delete_success': 'ลบบัญชีสำเร็จ',
  'account.delete_success_desc': 'บัญชีของคุณถูกลบเรียบร้อยแล้ว',
  'account.delete_error': 'เกิดข้อผิดพลาด',
  'account.delete_error_desc': 'ไม่สามารถลบบัญชีได้ กรุณาลองใหม่อีกครั้ง',
  
  // Terms Page
  'terms.title': 'เงื่อนไขการใช้บริการและนโยบาย',
  'terms.heading': 'Truckers  นโยบายความเป็นส่วนตัวของผู้ขับรถ',
  'terms.updated_date': 'มีผลบังคับเมื่อวันที่ 15 มกราคม 2567',
  'terms.collection_title': 'ข้อมูลที่เรารวบรวม',
  'terms.collection_intro': 'เรารวบรวมข้อมูลที่จำเป็นสำหรับการให้บริการแอป Truckers แก่ผู้ขับรถ ซึ่งรวมถึงข้อมูลที่คุณให้ไว้โดยตรงและข้อมูลที่เรารวบรวมจากการใช้แอป เช่น:',
  'terms.personal_data': 'ข้อมูลส่วนบุคคล :',
  'terms.personal_data_desc': 'เช่น ชื่อ, อีเมล, เบอร์โทรศัพท์, และข้อมูลบัญชีที่เกี่ยวข้องกับการขนส่ง',
  'terms.technical_data': 'ข้อมูลทางเทคนิค :',
  'terms.technical_data_desc': 'รวมถึงข้อมูลเกี่ยวกับการเดินทาง, ตำแหน่งที่ตั้ง (GPS), ความเร็ว, เส้นทางที่เลือก, เวลาเริ่มต้นและสิ้นสุดการขนส่ง',
  'terms.price_data': 'ข้อมูลราคา :',
  'terms.price_data_desc': 'รวมถึงหมายเลขทะเบียนรถ, ประเภทของรถ, และข้อมูลที่เกี่ยวข้องกับสภาพของรถบรรทุก',
  'terms.financial_data': 'ข้อมูลทางการเงิน :',
  'terms.financial_data_desc': 'ข้อมูลใช้สำหรับการชำระเงิน เช่น รายละเอียดบัญชีธนาคารหรือข้อมูลบัตรเครดิต',
  'terms.communication_data': 'ข้อมูลการสื่อสาร :',
  'terms.communication_data_desc': 'ข้อความ, การพูดคุย, หรือการติดต่อผ่านแอปที่เกี่ยวข้องกับการให้บริการ',
  'terms.usage_title': 'วิธีการใช้ข้อมูล',
  'terms.usage_intro': 'เราจะใช้ข้อมูลของคุณในหลายๆ ด้าน เช่น:',
  'terms.usage_1': 'การประมวลผลคำขอนส่งสินค้า',
  'terms.usage_2': 'การคำนวณค่าบริการและการชำระเงิน',
  'terms.usage_3': 'การปรับปรุงการให้บริการและการพัฒนาแอป',
  'terms.usage_4': 'การติดต่อคุณเพื่อให้ข้อมูลเกี่ยวกับสถานะการขนส่ง หรือแจ้งเตือน',
  'terms.usage_5': 'การปรับปรุงประสบการณ์การใช้งานของคุณ',
  'terms.usage_6': 'การปฏิบัติตามข้อกำหนดทางกฎหมาย',
  'terms.sharing_title': 'การแชร์ข้อมูล',
  'terms.sharing_intro': 'เราจะไม่แชร์ข้อมูลส่วนบุคคลของคุณกับบุคคลภายนอก ยกเว้นในกรณีดังต่อไปนี้:',
  'terms.sharing_provider': 'ผู้ให้บริการที่เราจ้าง:',
  'terms.sharing_provider_desc': 'บริษัทหรือบุคคลที่เราใช้บริการในด้านต่างๆ (เช่น บริการชำระเงิน, การวิเคราะห์ข้อมูล) ซึ่งมีข้อกำหนดความเป็นส่วนตัวที่ป้องกันข้อมูลของคุณ',
  'terms.sharing_legal': 'การปฏิบัติตามกฎหมาย:',
  'terms.sharing_legal_desc': 'ในกรณีที่เราถูกบังคับตามกฎหมาย',
  
  // Chat Page
  'chat.title': 'แชท',
  'chat.search': 'ค้นหาข้อความ',
  'chat.company': 'บริษัท',
  'chat.friends': 'เพื่อน',
  'chat.groups': 'กลุ่ม',
  'chat.online': 'ออนไลน์',
  'chat.offline': 'ออฟไลน์',
  'chat.typeMessage': 'พิมพ์ข้อความ',
  'chat.welcomeGroup': 'ยินดีต้อนรับกลุ่มสนทนา กับเพื่อนของคุณ!',
  'chat.addMembers': 'เพิ่มสมาชิก',
  'chat.memberList': 'รายชื่อสมาชิก',
  'chat.filesMedia': 'ไฟล์ รูปและวีดีโอ',
  'chat.muteNotifications': 'เปิดการแจ้งเตือน',
  'chat.deleteConversation': 'ลบการสนทนา',
  'chat.error': 'เกิดข้อผิดพลาด',
  'chat.sendError': 'ไม่สามารถส่งข้อความได้',
  'chat.muted': 'ปิดเสียงแล้ว',
  'chat.mutedDesc': 'คุณจะไม่ได้รับการแจ้งเตือนจากการสนทนานี้',
  'chat.createGroup': 'สร้างกลุ่มใหม่',
  'chat.groupName': 'ชื่อกลุ่ม',
  'chat.groupNamePlaceholder': 'ใส่ชื่อกลุ่ม',
  'chat.groupNameRequired': 'กรุณาใส่ชื่อกลุ่ม',
  'chat.selectMembers': 'เลือกสมาชิก',
  'chat.searchMembers': 'ค้นหาสมาชิก...',
  'chat.selectMembersRequired': 'กรุณาเลือกสมาชิกอย่างน้อย 1 คน',
  'chat.selectedCount': 'เลือกแล้ว',
  'chat.cancel': 'ยกเลิก',
  'chat.create': 'สร้าง',
  'chat.creating': 'กำลังสร้าง...',
  'chat.success': 'สำเร็จ',
  'chat.groupCreated': '🎉 สร้างกลุ่มแล้ว',
  'chat.groupCreatedSuccess': 'สร้างกลุ่มสำเร็จ',
  'chat.groupCreatedError': 'ไม่สามารถสร้างกลุ่มได้',
  'chat.noMembersFound': 'ไม่พบสมาชิก',
  'chat.manageGroup': 'จัดการกลุ่ม',
  'chat.info': 'ข้อมูล',
  'chat.members': 'สมาชิก',
  'chat.you': 'คุณ',
  'chat.groupNameUpdated': 'อัปเดตชื่อกลุ่มแล้ว',
  'chat.updateError': 'ไม่สามารถอัปเดตได้',
  'chat.membersAdded': 'เพิ่มสมาชิกแล้ว',
  'chat.addMembersError': 'ไม่สามารถเพิ่มสมาชิกได้',
  'chat.memberRemoved': 'ลบสมาชิกแล้ว',
  'chat.removeMemberError': 'ไม่สามารถลบสมาชิกได้',
  'chat.cannotRemoveSelf': 'ไม่สามารถลบตัวเองออกจากกลุ่มได้',
  'chat.adding': 'กำลังเพิ่ม...',
  'chat.addSelected': 'เพิ่มที่เลือก',
};

// English translations
const enTranslations: Record<string, string> = {
  // Settings Page
  'settings.title': 'Settings',
  'settings.profile': 'Profile',
  'settings.personal_info': 'Personal Information',
  'settings.account': 'Account',
  'settings.vehicle_info': 'Vehicle Information',
  'settings.general': 'General',
  'settings.notifications': 'Notifications',
  'settings.notifications_enabled': 'Notifications On',
  'settings.notifications_disabled': 'Notifications Off',
  'settings.about': 'About App',
  'settings.language': 'Language',
  'settings.terms': 'Terms of Service and Policy',
  'settings.contact': 'Contact Center',
  'settings.sign_out': 'Sign Out',
  'settings.sign_out_confirm': 'Do you want to sign out?',
  'settings.sign_out_description': 'Signing out will require you to log in again next time. Please confirm sign out.',
  'settings.cancel': 'Cancel',
  
  // Language Page
  'language.title': 'Language',
  'language.thai': 'ภาษาไทย',
  'language.english': 'English',
  
  // Bottom Navigation
  'nav.home': 'Home',
  'nav.dashboard': 'Dashboard',
  'nav.chat': 'Chat',
  'nav.settings': 'Settings',
  
  // Home Page
  'home.search': 'Search',
  'home.recommended': 'Recommended Jobs for You',
  'home.items': 'items',
  'home.error_load': 'Error',
  'home.error_load_desc': 'Unable to load jobs',
  'home.error_accept': 'Unable to accept job',
  'home.accept_success': 'Job Accepted',
  'home.accept_success_desc': 'You have accepted job',
  'home.greeting': '👋',
  'home.sunday': 'Sunday',
  'home.monday': 'Monday',
  'home.tuesday': 'Tuesday',
  'home.wednesday': 'Wednesday',
  'home.thursday': 'Thursday',
  'home.friday': 'Friday',
  'home.saturday': 'Saturday',
  'home.current_jobs': 'Current Jobs',
  'home.bidding': 'Bidding',
  'home.income': 'Income',
  'home.job_history': 'Job History',
  'home.sign_out_confirm': 'Do you want to sign out?',
  'home.sign_out_desc': 'Signing out will require you to log in again next time. Please confirm sign out.',
  'home.sign_out_btn': 'Sign Out',
  'home.cancel': 'Cancel',
  
  // Job Card
  'job.order_code': 'Order Code',
  'job.employer': 'Employer',
  'job.domestic': 'Domestic Transport',
  'job.international': 'International Transport',
  'job.inbound': 'Inbound',
  'job.outbound': 'Outbound',
  'job.origin': 'Origin',
  'job.destination': 'Destination',
  'job.equipment': 'Vehicle Equipment',
  'job.safety': 'Safety Equipment',
  'job.accept': 'Accept Job',
  'job.accepted': 'Job Accepted',
  
  // Confirm Job Dialog
  'confirm.title': 'Confirm Job Acceptance',
  'confirm.order_code': 'Order Code',
  'confirm.employer': 'Employer',
  'confirm.message': 'If you want to accept this job, please "Confirm"',
  'confirm.cancel': 'Cancel',
  'confirm.confirm': 'Confirm',
  
  // Dashboard Page
  'dashboard.finance': 'Finance (Expenses)',
  'dashboard.finance_desc': 'Track income and expenses easily',
  'dashboard.shipping': 'Shipping',
  'dashboard.shipping_desc': 'Check your shipments',
  'dashboard.customer': 'Customer',
  'dashboard.customer_desc': 'View your customer information',
  'dashboard.product': 'Product',
  'dashboard.product_desc': 'View product type information',
  'dashboard.view': 'View',
  
  // Search Page
  'search.title': 'Search',
  'search.search': 'Search',
  'search.results': 'Search Results',
  'search.no_results': 'No results found',
  'search.recent': 'Recent Searches',
  'search.popular': 'Popular Searches',
  'search.filter': 'Filter',
  'search.filter_desc': 'Filter search results',
  'search.domestic': 'Domestic Transport',
  'search.international': 'International Transport',
  'search.province': 'Province',
  'search.district': 'District',
  'search.select_province': 'Select Province',
  'search.select_district': 'Select District',
  'search.select_district_first': 'Please select province first',
  'search.price_range': 'Price Range (฿)',
  'search.min_price': 'Enter minimum price',
  'search.max_price': 'Enter maximum price',
  'search.clear': 'Clear',
  'search.apply': 'Search',
  
  // Profile Page
  'profile.title': 'Profile',
  'profile.first_name': 'First Name',
  'profile.last_name': 'Last Name',
  'profile.phone': 'Phone Number',
  'profile.email': 'Email',
  'profile.work_areas': 'Districts or provinces you work regularly',
  'profile.price_range': 'Job Price Range (฿)',
  'profile.change_avatar': 'Confirm Profile Picture Change',
  'profile.change_avatar_desc': 'Do you want to change your profile picture to this one?',
  'profile.confirm': 'Confirm',
  'profile.cancel': 'Cancel',
  'profile.uploading': 'Uploading...',
  'profile.error_upload': 'Unable to upload image',
  'profile.error_update': 'Unable to update profile',
  'profile.success': 'Success',
  'profile.success_desc': 'Profile picture updated',
  
  // Account Page
  'account.title': 'Account',
  'account.username': 'Username',
  'account.no_data': 'No data',
  'account.password': 'Password',
  'account.delete': 'Delete Account',
  'account.delete_confirm': 'Are you sure you want to delete your account?',
  'account.delete_desc': 'Deleting this account will remove all data',
  'account.delete_personal': 'Personal information',
  'account.delete_history': 'Service history',
  'account.delete_transactions': 'All transaction data',
  'account.delete_warning': 'Account deletion cannot be undone',
  'account.deleting': 'Deleting...',
  'account.cancel': 'Cancel',
  'account.delete_success': 'Account Deleted Successfully',
  'account.delete_success_desc': 'Your account has been deleted',
  'account.delete_error': 'Error',
  'account.delete_error_desc': 'Unable to delete account. Please try again.',
  
  // Terms Page
  'terms.title': 'Terms of Service and Policy',
  'terms.heading': 'Truckers  Privacy Policy for Drivers',
  'terms.updated_date': 'Effective as of January 15, 2024',
  'terms.collection_title': 'Data We Collect',
  'terms.collection_intro': 'We collect information necessary to provide the Truckers app services to drivers. This includes information you provide directly and information we collect from your use of the app, such as:',
  'terms.personal_data': 'Personal Data:',
  'terms.personal_data_desc': 'Such as name, email, phone number, and account information related to transportation',
  'terms.technical_data': 'Technical Data:',
  'terms.technical_data_desc': 'Including trip data, location (GPS), speed, route selection, start and end times of transportation',
  'terms.price_data': 'Price Data:',
  'terms.price_data_desc': 'Including vehicle registration number, vehicle type, and information related to truck condition',
  'terms.financial_data': 'Financial Data:',
  'terms.financial_data_desc': 'Data used for payment such as bank account details or credit card information',
  'terms.communication_data': 'Communication Data:',
  'terms.communication_data_desc': 'Messages, conversations, or communications through the app related to service provision',
  'terms.usage_title': 'How We Use Data',
  'terms.usage_intro': 'We will use your data in various ways, such as:',
  'terms.usage_1': 'Processing transportation request submissions',
  'terms.usage_2': 'Calculating service fees and payment',
  'terms.usage_3': 'Improving service provision and app development',
  'terms.usage_4': 'Contacting you to provide information about transportation status or notifications',
  'terms.usage_5': 'Improving your user experience',
  'terms.usage_6': 'Complying with legal requirements',
  'terms.sharing_title': 'Data Sharing',
  'terms.sharing_intro': 'We will not share your personal data with third parties, except in the following cases:',
  'terms.sharing_provider': 'Service Providers We Hire:',
  'terms.sharing_provider_desc': 'Companies or individuals we use for services in various areas (such as payment services, data analysis) that have privacy terms to protect your data',
  'terms.sharing_legal': 'Legal Compliance:',
  'terms.sharing_legal_desc': 'In cases where we are legally obligated',
  
  // Chat Page
  'chat.title': 'Chat',
  'chat.search': 'Search conversations',
  'chat.company': 'Company',
  'chat.friends': 'Friends',
  'chat.groups': 'Groups',
  'chat.online': 'Online',
  'chat.offline': 'Offline',
  'chat.typeMessage': 'Type a message',
  'chat.welcomeGroup': 'Welcome to the group chat with your friends!',
  'chat.addMembers': 'Add Members',
  'chat.memberList': 'Member List',
  'chat.filesMedia': 'Files and Media',
  'chat.muteNotifications': 'Mute Notifications',
  'chat.deleteConversation': 'Delete Conversation',
  'chat.error': 'Error',
  'chat.sendError': 'Failed to send message',
  'chat.muted': 'Muted',
  'chat.mutedDesc': 'You will no longer receive notifications from this conversation',
  'chat.createGroup': 'Create New Group',
  'chat.groupName': 'Group Name',
  'chat.groupNamePlaceholder': 'Enter group name',
  'chat.groupNameRequired': 'Please enter group name',
  'chat.selectMembers': 'Select Members',
  'chat.searchMembers': 'Search members...',
  'chat.selectMembersRequired': 'Please select at least 1 member',
  'chat.selectedCount': 'Selected',
  'chat.cancel': 'Cancel',
  'chat.create': 'Create',
  'chat.creating': 'Creating...',
  'chat.success': 'Success',
  'chat.groupCreated': '🎉 Group created',
  'chat.groupCreatedSuccess': 'Group created successfully',
  'chat.groupCreatedError': 'Failed to create group',
  'chat.noMembersFound': 'No members found',
  'chat.manageGroup': 'Manage Group',
  'chat.info': 'Info',
  'chat.members': 'Members',
  'chat.you': 'You',
  'chat.groupNameUpdated': 'Group name updated',
  'chat.updateError': 'Failed to update',
  'chat.membersAdded': 'Members added',
  'chat.addMembersError': 'Failed to add members',
  'chat.memberRemoved': 'Member removed',
  'chat.removeMemberError': 'Failed to remove member',
  'chat.cannotRemoveSelf': 'Cannot remove yourself from group',
  'chat.adding': 'Adding...',
  'chat.addSelected': 'Add Selected',
};
