import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'th';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    const translations = language === 'th' ? thTranslations : enTranslations;
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Thai translations
const thTranslations: Record<string, string> = {
  // Settings Page
  'settings.title': 'ตั้งค่า',
  'settings.profile': 'โปรไฟล์',
  'settings.personal_info': 'ข้อมูลส่วนตัว',
  'settings.account': 'บัญชี',
  'settings.vehicle_info': 'ข้อมูลรถ',
  'settings.general': 'ทั่วไป',
  'settings.notifications': 'การแจ้งเตือน',
  'settings.notifications_enabled': 'เปิดแจ้งเตือน',
  'settings.notifications_disabled': 'ปิดแจ้งเตือน',
  'settings.about': 'ข้อมูลเกี่ยวกับแอป',
  'settings.language': 'ภาษา',
  'settings.terms': 'เงื่อนไขการใช้บริการและนโยบาย',
  'settings.contact': 'ติดต่อศูนย์',
  'settings.sign_out': 'ออกจากระบบ',
  'settings.sign_out_confirm': 'คุณต้องการออกจากระบบหรือไม่?',
  'settings.sign_out_description': 'การออกจากระบบจะทำให้คุณต้องล็อกอินเข้าสู่ระบบอีกครั้ง ในครั้งถัดไป กรุณายืนยันออกจากระบบ',
  'settings.cancel': 'ยกเลิก',
  
  // Language Page
  'language.title': 'ภาษา',
  'language.thai': 'ภาษาไทย',
  'language.english': 'English',
  
  // Bottom Navigation
  'nav.home': 'หน้าแรก',
  'nav.dashboard': 'แผงควบคุม',
  'nav.chat': 'แชท',
  'nav.settings': 'ตั้งค่า',
  
  // Home Page
  'home.search': 'ค้นหา',
  'home.recommended': 'งานแนะนำสำหรับคุณ',
  'home.items': 'รายการ',
  'home.error_load': 'เกิดข้อผิดพลาด',
  'home.error_load_desc': 'ไม่สามารถโหลดข้อมูลงานได้',
  'home.error_accept': 'ไม่สามารถรับงานได้',
  'home.accept_success': 'รับงานสำเร็จ',
  'home.accept_success_desc': 'คุณได้รับงาน',
  'home.greeting': '👋',
  'home.sunday': 'วันอาทิตย์',
  'home.monday': 'วันจันทร์',
  'home.tuesday': 'วันอังคาร',
  'home.wednesday': 'วันพุธ',
  'home.thursday': 'วันพฤหัสบดี',
  'home.friday': 'วันศุกร์',
  'home.saturday': 'วันเสาร์',
  'home.current_jobs': 'งานปัจจุบัน',
  'home.bidding': 'เสนอราคา',
  'home.income': 'รายได้',
  'home.job_history': 'ประวัติงาน',
  'home.sign_out_confirm': 'คุณต้องการออกจากระบบหรือไม่?',
  'home.sign_out_desc': 'การออกจากระบบจะทำให้คุณต้องล็อกอินเข้าสู่ระบบอีกครั้ง ในครั้งถัดไป กรุณายืนยันออกจากระบบ',
  'home.sign_out_btn': 'ออกจากระบบ',
  'home.cancel': 'ยกเลิก',
  
  // Job Card
  'job.order_code': 'รหัสออเดอร์',
  'job.employer': 'ผู้จ้าง',
  'job.domestic': 'ขนส่งภายในประเทศ',
  'job.international': 'ขนส่งภายนอกประเทศ',
  'job.inbound': 'ขาเข้า',
  'job.outbound': 'ขาออก',
  'job.origin': 'ต้นทาง',
  'job.destination': 'ปลายทาง',
  'job.equipment': 'อุปกรณ์ติดรถ',
  'job.safety': 'อุปกรณ์ Safety',
  'job.accept': 'รับงานนี้',
  'job.accepted': 'รับงานนี้แล้ว',
  
  // Confirm Job Dialog
  'confirm.title': 'ยืนยันการรับงาน',
  'confirm.order_code': 'รหัสออเดอร์',
  'confirm.employer': 'ผู้จ้าง',
  'confirm.message': 'หากคุณต้องการรับรถงานที่ "ยืนยัน"',
  'confirm.cancel': 'ยกเลิก',
  'confirm.confirm': 'ยืนยัน',
  
  // Job History Page
  'jobHistory.title': 'ประวัติงาน',
  'jobHistory.all': 'ทั้งหมด',
  'jobHistory.inProgress': 'กำลังส่ง',
  'jobHistory.completed': 'เสร็จสิ้น',
  'jobHistory.selectMonth': 'เลือกเดือน',
  'jobHistory.allMonths': 'ทุกเดือน',
  'jobHistory.january': 'มกราคม',
  'jobHistory.february': 'กุมภาพันธ์',
  'jobHistory.march': 'มีนาคม',
  'jobHistory.april': 'เมษายน',
  'jobHistory.may': 'พฤษภาคม',
  'jobHistory.june': 'มิถุนายน',
  'jobHistory.july': 'กรกฎาคม',
  'jobHistory.august': 'สิงหาคม',
  'jobHistory.september': 'กันยายน',
  'jobHistory.october': 'ตุลาคม',
  'jobHistory.november': 'พฤศจิกายน',
  'jobHistory.december': 'ธันวาคม',
  'jobHistory.loading': 'กำลังโหลด...',
  'jobHistory.noData': 'ไม่พบประวัติงาน',
  'jobHistory.statusCompleted': 'เสร็จสิ้น',
  'jobHistory.statusDelivering': 'กำลังจัดส่ง',
  'jobHistory.statusAccepted': 'รับงานแล้ว',
  
  // Current Jobs Page
  'currentJobs.title': 'งานปัจจุบัน',
  'currentJobs.search': 'ค้นหา ชื่อ,ออเดอร์,รหัสออเดอร์',
  'currentJobs.empty': 'ยังไม่มีงานในตอนนี้',
  'currentJobs.viewDetails': 'ดูข้อมูลงาน',
  'currentJobs.filter': 'ตัวกรอง',
  'currentJobs.dateRange': 'วันเวลาที่รับมอบงาน',
  'currentJobs.startDate': 'วันที่เริ่มต้น',
  'currentJobs.endDate': 'วันที่สิ้นสุด',
  'currentJobs.clearFilter': 'ล้างค่า',
  'currentJobs.applyFilter': 'ค้นหา',
  'currentJobs.startJobDate': 'วันเริ่มงาน',
  'currentJobs.errorLoad': 'เกิดข้อผิดพลาด',
  'currentJobs.errorLoadDesc': 'ไม่สามารถโหลดข้อมูลงานได้',
  
  // Bidding Page
  'bidding.title': 'เสนอราคา',
  'bidding.biddingTab': 'เสนอราคา',
  'bidding.historyTab': 'ประวัติ',
  'bidding.noJobs': 'ไม่มีงานที่เปิดรับเสนอราคา',
  'bidding.placeBid': 'เริ่มเสนอราคา',
  'bidding.noHistory': 'ยังไม่มีประวัติการเสนอราคา',
  'bidding.bidAt': 'เสนอราคาเมื่อ',
  'bidding.statusPending': 'รอดำเนินการ',
  'bidding.statusAccepted': 'เสร็จสิ้น',
  'bidding.statusRejected': 'ปฏิเสธ',
  'bidding.monthLabel': 'กุมภาพันธ์',
  
  // Income Page
  'income.title': 'รายได้ของฉัน',
  'income.all': 'ทั้งหมด',
  'income.paid': 'ชำระแล้ว',
  'income.unpaid': 'ยังไม่ชำระ',
  'income.selectMonth': 'เลือกเดือน',
  'income.viewDetails': 'ดูข้อมูลงาน',
  'income.noData': 'ไม่มีข้อมูลรายได้',
  'income.noPaid': 'ไม่มีงานที่ชำระแล้ว',
  'income.noUnpaid': 'ไม่มีงานที่ยังไม่ชำระ',
  'income.errorLoad': 'เกิดข้อผิดพลาด',
  'income.errorLoadDesc': 'ไม่สามารถโหลดข้อมูลรายได้ได้',
  
  // Dashboard Page
  'dashboard.finance': 'การเงิน (ค่าใช้จ่าย)',
  'dashboard.finance_desc': 'ติดตามรายรับ, รายจ่าย ได้ง่าย',
  'dashboard.shipping': 'การจัดส่ง',
  'dashboard.shipping_desc': 'ตรวจสอบการจัดส่งของคุณ',
  'dashboard.customer': 'ลูกค้า',
  'dashboard.customer_desc': 'ดูข้อมูลลูกค้าของคุณ',
  'dashboard.product': 'สินค้า',
  'dashboard.product_desc': 'ดูข้อมูลประเภทสินค้า',
  'dashboard.view': 'ดู',

  // Finance Page
  'finance.title': 'การเงิน',
  'finance.day': 'วัน',
  'finance.month': 'เดือน',
  'finance.year': 'ปี',
  'finance.profit': 'กำไร',
  'finance.expenses': 'ค่าใช้จ่าย',
  'finance.total_income': 'รายได้ทั้งหมด',
  'finance.compare_year': 'เปรียบเทียบกับปี: 2566',
  'finance.buddhist_era': 'พ.ศ.',
  'finance.income': 'รายได้',
  'finance.pending_payments': 'รายได้ค้างชำระ',
  'finance.companies': 'บริษัท',

  // Shipping Page
  'shipping.title': 'การจัดส่ง',
  'shipping.all_types': 'ทุกประเภทการขนส่ง',
  'shipping.tractor': 'หัวลาก',
  'shipping.12wheels': '12 ล้อ',
  'shipping.10wheels': '10 ล้อ',
  'shipping.6wheels': '6 ล้อ',
  'shipping.4wheels': '4 ล้อ',
  'shipping.job_data': 'ข้อมูลงานจัดส่ง',
  'shipping.all_jobs': 'งานทั้งหมด',
  'shipping.success': 'สำเร็จ',
  'shipping.in_delivery': 'กำลังจัดส่ง',
  'shipping.cancelled': 'ยกเลิก',
  'shipping.by_region': 'การขนส่งแต่ละภาค',
  'shipping.north': 'ภาคเหนือ',
  'shipping.central': 'ภาคกลาง',
  'shipping.northeast': 'ภาคอีสาน',
  'shipping.east': 'ภาคตะวันออก',
  'shipping.west': 'ภาคตะวันตก',
  'shipping.south': 'ภาคใต้',

  // Customer Page
  'customer.title': 'ลูกค้า',
  'customer.top_5': '5 อันดับสูงสุด',
  'customer.jobs': 'งาน',

  // Product Page
  'product.title': 'สินค้า',
  'product.product_types': 'ประเภทสินค้า',
  'product.top_5': '5 อันดับสูงสุด',
  'product.jobs': 'งาน',
  
  // Search Page
  'search.title': 'ค้นหา',
  'search.search': 'ค้นหา',
  'search.results': 'ผลการค้นหา',
  'search.no_results': 'ไม่พบผลการค้นหา',
  'search.recent': 'คำค้นหาล่าสุด',
  'search.popular': 'คำค้นหายอดนิยม',
  'search.filter': 'ตัวกรอง',
  'search.filter_desc': 'กรองผลการค้นหา',
  'search.domestic': 'ขนส่งภายในประเทศ',
  'search.international': 'ขนส่งภายนอกประเทศ',
  'search.province': 'จังหวัด',
  'search.district': 'อำเภอ',
  'search.select_province': 'เลือกจังหวัด',
  'search.select_district': 'เลือกอำเภอ',
  'search.select_district_first': 'กรุณาเลือกจังหวัดก่อน',
  'search.price_range': 'ช่วงราคา (฿)',
  'search.min_price': 'ใส่ราคาต่ำสุด',
  'search.max_price': 'ใส่ราคาสูงสุด',
  'search.clear': 'ล้างค่า',
  'search.apply': 'ค้นหา',
  
  // Profile Page
  'profile.title': 'โปรไฟล์',
  'profile.first_name': 'ชื่อ',
  'profile.last_name': 'นามสกุล',
  'profile.phone': 'เบอร์โทรศัพท์',
  'profile.email': 'อีเมล',
  'profile.work_areas': 'อำเภอ หรือ จังหวัด ที่ถนัดหรือจังหวัดทั่วเป็นประจำ',
  'profile.price_range': 'เรทราคาวังงาน (฿)',
  'profile.change_avatar': 'ยืนยันการเปลี่ยนรูปโปรไฟล์',
  'profile.change_avatar_desc': 'คุณต้องการเปลี่ยนรูปโปรไฟล์เป็นรูปนี้หรือไม่?',
  'profile.confirm': 'ยืนยัน',
  'profile.cancel': 'ยกเลิก',
  'profile.uploading': 'กำลังอัพโหลด...',
  'profile.error_upload': 'ไม่สามารถอัพโหลดรูปภาพได้',
  'profile.error_update': 'ไม่สามารถอัพเดทโปรไฟล์ได้',
  'profile.success': 'สำเร็จ',
  'profile.success_desc': 'อัพเดทรูปโปรไฟล์แล้ว',
  
  // Account Page
  'account.title': 'บัญชี',
  'account.username': 'ชื่อผู้ใช้',
  'account.no_data': 'ไม่มีข้อมูล',
  'account.password': 'รหัสผ่าน',
  'account.delete': 'ลบบัญชี',
  'account.delete_confirm': 'คุณกำลังจะลบบัญชีใช่ไหม',
  'account.delete_desc': 'การลบบัญชีนี้จะเป็นการลบข้อมูลทั้งหมด',
  'account.delete_personal': 'ข้อมูลส่วนตัว',
  'account.delete_history': 'ประวัติการใช้บริการ',
  'account.delete_transactions': 'ข้อมูลธุรกรรมทั้งหมด',
  'account.delete_warning': 'หลังจากลบบัญชีแล้วจะไม่สามารถกู้คืนได้',
  'account.deleting': 'กำลังลบ...',
  'account.cancel': 'ยกเลิก',
  'account.delete_success': 'ลบบัญชีสำเร็จ',
  'account.delete_success_desc': 'บัญชีของคุณถูกลบเรียบร้อยแล้ว',
  'account.delete_error': 'เกิดข้อผิดพลาด',
  'account.delete_error_desc': 'ไม่สามารถลบบัญชีได้ กรุณาลองใหม่อีกครั้ง',
  
  // Terms Page
  'terms.title': 'เงื่อนไขการใช้บริการและนโยบาย',
  'terms.heading': 'Truckers  นโยบายความเป็นส่วนตัวของผู้ขับรถ',
  'terms.updated_date': 'มีผลบังคับเมื่อวันที่ 15 มกราคม 2567',
  'terms.collection_title': 'ข้อมูลที่เรารวบรวม',
  'terms.collection_intro': 'เรารวบรวมข้อมูลที่จำเป็นสำหรับการให้บริการแอป Truckers แก่ผู้ขับรถ ซึ่งรวมถึงข้อมูลที่คุณให้ไว้โดยตรงและข้อมูลที่เรารวบรวมจากการใช้แอป เช่น:',
  'terms.personal_data': 'ข้อมูลส่วนบุคคล :',
  'terms.personal_data_desc': 'เช่น ชื่อ, อีเมล, เบอร์โทรศัพท์, และข้อมูลบัญชีที่เกี่ยวข้องกับการขนส่ง',
  'terms.technical_data': 'ข้อมูลทางเทคนิค :',
  'terms.technical_data_desc': 'รวมถึงข้อมูลเกี่ยวกับการเดินทาง, ตำแหน่งที่ตั้ง (GPS), ความเร็ว, เส้นทางที่เลือก, เวลาเริ่มต้นและสิ้นสุดการขนส่ง',
  'terms.price_data': 'ข้อมูลราคา :',
  'terms.price_data_desc': 'รวมถึงหมายเลขทะเบียนรถ, ประเภทของรถ, และข้อมูลที่เกี่ยวข้องกับสภาพของรถบรรทุก',
  'terms.financial_data': 'ข้อมูลทางการเงิน :',
  'terms.financial_data_desc': 'ข้อมูลใช้สำหรับการชำระเงิน เช่น รายละเอียดบัญชีธนาคารหรือข้อมูลบัตรเครดิต',
  'terms.communication_data': 'ข้อมูลการสื่อสาร :',
  'terms.communication_data_desc': 'ข้อความ, การพูดคุย, หรือการติดต่อผ่านแอปที่เกี่ยวข้องกับการให้บริการ',
  'terms.usage_title': 'วิธีการใช้ข้อมูล',
  'terms.usage_intro': 'เราจะใช้ข้อมูลของคุณในหลายๆ ด้าน เช่น:',
  'terms.usage_1': 'การประมวลผลคำขอนส่งสินค้า',
  'terms.usage_2': 'การคำนวณค่าบริการและการชำระเงิน',
  'terms.usage_3': 'การปรับปรุงการให้บริการและการพัฒนาแอป',
  'terms.usage_4': 'การติดต่อคุณเพื่อให้ข้อมูลเกี่ยวกับสถานะการขนส่ง หรือแจ้งเตือน',
  'terms.usage_5': 'การปรับปรุงประสบการณ์การใช้งานของคุณ',
  'terms.usage_6': 'การปฏิบัติตามข้อกำหนดทางกฎหมาย',
  'terms.sharing_title': 'การแชร์ข้อมูล',
  'terms.sharing_intro': 'เราจะไม่แชร์ข้อมูลส่วนบุคคลของคุณกับบุคคลภายนอก ยกเว้นในกรณีดังต่อไปนี้:',
  'terms.sharing_provider': 'ผู้ให้บริการที่เราจ้าง:',
  'terms.sharing_provider_desc': 'บริษัทหรือบุคคลที่เราใช้บริการในด้านต่างๆ (เช่น บริการชำระเงิน, การวิเคราะห์ข้อมูล) ซึ่งมีข้อกำหนดความเป็นส่วนตัวที่ป้องกันข้อมูลของคุณ',
  'terms.sharing_legal': 'การปฏิบัติตามกฎหมาย:',
  'terms.sharing_legal_desc': 'ในกรณีที่เราถูกบังคับตามกฎหมาย เช่น การให้ข้อมูลแก่หน่วยงานราชการ หรือการปฏิบัติตามคำสั่งศาล',
  'terms.sharing_anonymous': 'การแชร์ข้อมูลที่ไม่สามารถระบุตัวตน:',
  'terms.sharing_anonymous_desc': 'เช่น ข้อมูลทางสถิติที่ไม่ระบุตัวตนหรือข้อมูลที่ใช้ในการวิเคราะห์เพื่อพัฒนาแอป',
  
  // Job Detail Page
  'jobDetail.error': 'เกิดข้อผิดพลาด',
  'jobDetail.errorLoadDesc': 'ไม่สามารถโหลดข้อมูลงานได้',
  'jobDetail.notFound': 'ไม่พบข้อมูลงานนี้',
  'jobDetail.invalidType': 'ประเภทงานไม่ถูกต้อง',
  'jobDetail.domestic': 'ขนส่งภายในประเทศ',
  'jobDetail.international': 'ขนส่งภายนอกประเทศ',
  'jobDetail.inbound': 'ขาเข้า',
  'jobDetail.outbound': 'ขาออก',
  'jobDetail.reportProblem': 'แจ้งปัญหา',
  'jobDetail.booking': 'Booking',
  'jobDetail.employer': 'ผู้จ้าง',
  'jobDetail.pickupPoint': 'จุดรับสินค้า',
  'jobDetail.deliveryPoint': 'จุดส่งสินค้า',
  'jobDetail.sopSuccess': 'SOP สำเร็จ',
  'jobDetail.waitingSop': 'รอ SOP',
  'jobDetail.waitingCheckIn': 'รอเช็คอิน',
  'jobDetail.podSuccess': 'POD สำเร็จ',
  'jobDetail.waitingPod': 'รอ POD',
  'jobDetail.contactPerson': 'ชื่อผู้ติดต่อ',
  'jobDetail.position': 'ตำแหน่ง',
  'jobDetail.goodsType': 'ประเภทสินค้า',
  'jobDetail.pickupTime': 'เข้ารับสินค้า',
  'jobDetail.deliveryTime': 'ส่งสินค้า',
  'jobDetail.remarks': 'หมายเหตุ',
  'jobDetail.call': 'โทร',
  'jobDetail.route': 'เส้นทาง',
  'jobDetail.viewInfo': 'ดูข้อมูล',
  'jobDetail.updateStatus': 'อัปเดตสถานะ',
  'jobDetail.startJob': 'เริ่มงาน',
  'jobDetail.startJobNow': 'เริ่มงานเลย',
  'jobDetail.pickupDeliveryPoints': 'จุดรับ/ส่ง',
  'jobDetail.errorStartJob': 'ไม่สามารถเริ่มงานได้',
  'jobDetail.startJobSuccess': 'เริ่มงานสำเร็จ',
  'jobDetail.startJobSuccessDesc': 'คุณสามารถทำงานส่งของได้แล้ว',
  'jobDetail.containerCheckpoint': 'จุดรับตู้เปล่า',
  'jobDetail.containerSuccess': 'รับตู้เปล่าสำเร็จ',
  'jobDetail.waitingContainer': 'รอรับตู้เปล่า',
  'jobDetail.startDateTime': 'วัน/เวลาเริ่มต้น',
  'jobDetail.emptyContainerDate': 'วันรับเข้าช่างต้นต้น',
  'jobDetail.receiver': 'ผู้รับสินค้า',
  'jobDetail.containerDate': 'วันคนเทนเนอร์',
  'jobDetail.containerNumber': 'เลขตู้คอนเทนเนอร์',
  'jobDetail.sealNumber': 'เลขซีล',
  'jobDetail.loadingPoint': 'จุดรับสินค้า',
  'jobDetail.unloadingPoint': 'จุดส่งสินค้า',
  'jobDetail.billOfLading': 'เลขที่เอียด',
  'jobDetail.contactPoint': 'ชื่อจุดติดต่อ',
  'jobDetail.routeCode': 'เลขทาง',
  'jobDetail.deliveryRoute': 'เส้นทาง',
  'jobDetail.emptyReturn': 'จุดคืนตู้เปล่า',
  'jobDetail.fullReturn': 'จุดคืนตู้เต็ม',
  'jobDetail.returnDeadline': 'วันที่หมดคืนตู้เปล่า',
  'jobDetail.guarantor': 'ผู้รับรอง',
  'jobDetail.returnDate': 'วันคืนตู้คอนเทนเนอร์',
  'jobDetail.startJobDesc': 'คุณสามารถเริ่มตรวจตู้เปล่าได้แล้ว',

  // Chat Page
  'chat.title': 'แชท',
  'chat.search': 'ค้นหาข้อความ',
  'chat.company': 'บริษัท',
  'chat.friends': 'เพื่อน',
  'chat.groups': 'กลุ่ม',
  'chat.online': 'ออนไลน์',
  'chat.offline': 'ออฟไลน์',
  'chat.typeMessage': 'พิมพ์ข้อความ',
  'chat.welcomeGroup': 'ยินดีต้อนรับกลุ่มสนทนา กับเพื่อนของคุณ!',
  'chat.addMembers': 'เพิ่มสมาชิก',
  'chat.memberList': 'รายชื่อสมาชิก',
  'chat.filesMedia': 'ไฟล์ รูปและวีดีโอ',
  'chat.muteNotifications': 'เปิดการแจ้งเตือน',
  'chat.deleteConversation': 'ลบการสนทนา',
  'chat.error': 'เกิดข้อผิดพลาด',
  'chat.sendError': 'ไม่สามารถส่งข้อความได้',
  'chat.muted': 'ปิดเสียงแล้ว',
  'chat.mutedDesc': 'คุณจะไม่ได้รับการแจ้งเตือนจากการสนทนานี้',
  'chat.createGroup': 'สร้างกลุ่มใหม่',
  'chat.groupName': 'ชื่อกลุ่ม',
  'chat.groupNamePlaceholder': 'ใส่ชื่อกลุ่ม',
  'chat.groupNameRequired': 'กรุณาใส่ชื่อกลุ่ม',
  'chat.selectMembers': 'เลือกสมาชิก',
  'chat.searchMembers': 'ค้นหาสมาชิก...',
  'chat.selectMembersRequired': 'กรุณาเลือกสมาชิกอย่างน้อย 1 คน',
  'chat.selectedCount': 'เลือกแล้ว',
  'chat.cancel': 'ยกเลิก',
  'chat.create': 'สร้าง',
  'chat.creating': 'กำลังสร้าง...',
  'chat.success': 'สำเร็จ',
  'chat.groupCreated': '🎉 สร้างกลุ่มแล้ว',
  'chat.groupCreatedSuccess': 'สร้างกลุ่มสำเร็จ',
  'chat.groupCreatedError': 'ไม่สามารถสร้างกลุ่มได้',
  'chat.noMembersFound': 'ไม่พบสมาชิก',
  'chat.manageGroup': 'จัดการกลุ่ม',
  'chat.info': 'ข้อมูล',
  'chat.members': 'สมาชิก',
  'chat.you': 'คุณ',
  'chat.groupNameUpdated': 'อัปเดตชื่อกลุ่มแล้ว',
  'chat.updateError': 'ไม่สามารถอัปเดตได้',
  'chat.membersAdded': 'เพิ่มสมาชิกแล้ว',
  'chat.addMembersError': 'ไม่สามารถเพิ่มสมาชิกได้',
  'chat.memberRemoved': 'ลบสมาชิกแล้ว',
  'chat.removeMemberError': 'ไม่สามารถลบสมาชิกได้',
  'chat.cannotRemoveSelf': 'ไม่สามารถลบตัวเองออกจากกลุ่มได้',
  'chat.adding': 'กำลังเพิ่ม...',
  'chat.addSelected': 'เพิ่มที่เลือก',

  // Report Problem Drawer
  'reportProblem.title': 'แจ้งปัญหา',
  'reportProblem.problemAccident': 'แจ้งปัญหา/ อุบัติเหตุ',
  'reportProblem.partialDelivery': 'ส่งมอบสินค้าบางส่วน',
  'reportProblem.pauseWork': 'หยุดงานชั่วคราว',
  'reportProblem.reportIssue': 'แจ้งปัญหา',
  'reportProblem.specifyTime': 'ระบุเวลากล่อง',
  'reportProblem.specifyReason': 'ระบุสาเหตุ',
  'reportProblem.reasonPlaceholder': 'ระบุเหตุผล',
  'reportProblem.uploadPhoto': 'อัพโหลดรูปสินค้า',
  'reportProblem.clickToTake': 'กดเพื่อถ่ายหรือเลือก',
  'reportProblem.productPhoto': 'รูปสินค้า',
  'reportProblem.fileSelected': 'เลือกไฟล์',
  'reportProblem.downloadVehicleChange': 'ดาวน์โหลดใบเปลี่ยนรถ',
  'reportProblem.confirm': 'ยืนยัน',
  'reportProblem.fillAllFields': 'กรุณากรอกข้อมูลให้ครบถ้วน',
  
  // Job Action Buttons
  'jobActions.viewExpenses': 'ดูค่าใช้จ่าย',
  'jobActions.addExpense': 'เพิ่มค่าใช้จ่าย',
  'jobActions.reportProblem': 'แจ้งปัญหา',
  
  // Sign In Page
  'signIn.title': 'เข้าสู่ระบบหรือสมัครสมาชิก',
  'signIn.username': 'ชื่อผู้ใช้',
  'signIn.password': 'รหัสผ่าน',
  'signIn.rememberMe': 'จดจำฉันในระบบ',
  'signIn.forgotPassword': 'ลืมรหัสผ่านใช่หรือไป?',
  'signIn.signInButton': 'เข้าสู่ระบบ',
  'signIn.registerButton': 'ลงทะเบียน',
  'signIn.success': 'เข้าสู่ระบบสำเร็จ',
  'signIn.welcomeBack': 'ยินดีต้อนรับกลับมา',
  'signIn.error': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
  'signIn.invalidCredentials': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง',
  'signIn.validation.emailRequired': 'กรุณากรอกชื่อผู้ใช้',
  'signIn.validation.emailFormat': 'รูปแบบอีเมลไม่ถูกต้อง',
  'signIn.validation.passwordMin': 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร',
  
  // Register Page
  'register.steps.terms': 'เงื่อนไขการใช้บริการและนโยบาย',
  'register.steps.generalInfo': 'ข้อมูลทั่วไป',
  'register.steps.vehiclePhotos': 'อัพโหลดรูปรถ',
  'register.steps.vehicleInfo': 'ข้อมูลรถ',
  'register.steps.review': 'ตรวจสอบข้อมูล',
  'register.success': 'สมัครสมาชิกสำเร็จ!',
  'register.successDesc': 'ข้อมูลของคุณถูกบันทึกเรียบร้อยแล้ว',
  'register.error': 'เกิดข้อผิดพลาด',
  'register.errorDesc': 'กรุณาลองใหม่อีกครั้ง',
  'register.createAccountFailed': 'ไม่สามารถสร้างบัญชีได้ กรุณาลองใหม่อีกครั้ง',
  'register.createAccountError': 'ไม่สามารถสร้างบัญชีได้',
  'register.vehicleSaveFailed': 'บันทึกข้อมูลรถไม่สำเร็จ',
  
  // Terms Step (Register)
  'termsStep.title': 'Truckers นโยบายความเป็นส่วนตัวของผู้ขับรถ',
  'termsStep.effectiveDate': 'มีผลบังคับเมื่อวันที่ 15 มกราคม 2567',
  'termsStep.accept': 'ยอมรับ',
  'termsStep.scrollToAccept': 'เลื่อนลงจนสุดเพื่อดำเนินการต่อ',
  'termsStep.scrollMessage': 'กรุณาเลื่อนอ่านข้อกำหนดจนจบเพื่อดำเนินการต่อ',
  
  // General Info Step
  'generalInfo.profilePhoto': 'รูปภาพผู้ขับขี่',
  'generalInfo.selectPhoto': 'เลือกรูปภาพ',
  'generalInfo.takePhoto': 'ถ่ายภาพ',
  'generalInfo.takePhotoDesc': 'เปิดกล้องเพื่อถ่ายภาพ',
  'generalInfo.selectFromGallery': 'เลือกจากแกลลอรี่',
  'generalInfo.selectFromGalleryDesc': 'เลือกรูปภาพที่มีอยู่ในเครื่อง',
  'generalInfo.photoPrompt': 'กดเพื่อถ่ายรูปหรือเลือกรูปใบหน้า',
  'generalInfo.personalInfo': 'ข้อมูลส่วนตัว',
  'generalInfo.firstName': 'ชื่อ (ระบุชื่อตามบัตรประชาชน)',
  'generalInfo.lastName': 'นามสกุล (ระบุนามสกุลตามบัตรประชาชน)',
  'generalInfo.phone': 'เบอร์โทรศัพท์',
  'generalInfo.email': 'อีเมล',
  'generalInfo.userInfo': 'ข้อมูลผู้ใช้งาน',
  'generalInfo.username': 'ชื่อผู้ใช้',
  'generalInfo.password': 'รหัสผ่าน',
  'generalInfo.confirmPassword': 'ยืนยันรหัสผ่าน',
  'generalInfo.workArea': 'พื้นที่วิ่งงาน',
  'generalInfo.workAreaLabel': 'อำเภอ หรือ จังหวัด ที่ถนัดหรือวิ่งงานเป็นประจำ',
  'generalInfo.workAreaPlaceholder': 'ค้นหาอำเภอ/จังหวัด',
  'generalInfo.priceRange': 'เรทราคาวิ่งงาน (฿)',
  'generalInfo.priceMin': 'ใส่ราคาต่ำสุด',
  'generalInfo.priceMax': 'ใส่ราคาสูงสุด',
  'generalInfo.next': 'ต่อไป →',
  'generalInfo.validation.firstNameRequired': 'กรุณากรอกชื่อ',
  'generalInfo.validation.lastNameRequired': 'กรุณากรอกนามสกุล',
  'generalInfo.validation.phoneRequired': 'กรุณากรอกเบอร์โทรศัพท์ให้ถูกต้อง',
  'generalInfo.validation.emailFormat': 'รูปแบบอีเมลไม่ถูกต้อง',
  'generalInfo.validation.usernameRequired': 'กรุณากรอกชื่อผู้ใช้งาน',
  'generalInfo.validation.passwordMin': 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร',
  'generalInfo.validation.confirmPasswordMin': 'กรุณายืนยันรหัสผ่าน',
  'generalInfo.validation.passwordMismatch': 'รหัสผ่านไม่ตรงกัน',
  'generalInfo.validation.priceMinRequired': 'กรุณากรอกราคาต่ำสุด',
  'generalInfo.validation.priceMaxRequired': 'กรุณากรอกราคาสูงสุด',
  'generalInfo.validation.priceRange': 'กรุณากรอกช่วงราคา',
  
  // Vehicle Photos Step
  'vehiclePhotosStep.frontPhoto': 'รูปหน้ารถ',
  'vehiclePhotosStep.sidePhoto': 'รูปข้างรถ',
  'vehiclePhotosStep.backPhoto': 'รูปหลังรถ',
  'vehiclePhotosStep.platePhoto': 'รูปป้ายทะเบียน',
  'vehiclePhotosStep.hasTrailer': 'มีส่วนของหางลาก',
  'vehiclePhotosStep.trailerPlatePhoto': 'รูปภาพป้ายทะเบียนหางลาก',
  'vehiclePhotosStep.clickToTake': 'กดเพื่อถ่ายรูปหรือเลือกรูป',
  'vehiclePhotosStep.addPhoto': 'เพิ่มรูปภาพ',
  'vehiclePhotosStep.takePhoto': 'ถ่ายภาพ',
  'vehiclePhotosStep.selectFromGallery': 'เลือกรูปจากแกลลอรี่',
  'vehiclePhotosStep.cancel': 'ยกเลิก',
  'vehiclePhotosStep.back': 'ย้อนกลับ',
  'vehiclePhotosStep.next': 'ต่อไป →',
  
  // Vehicle Info Step
  'vehicleInfoStep.plateNumber': 'หมายเลขทะเบียน (ไม่เว้นวรรคไม่ใส่ขีด)',
  'vehicleInfoStep.plateProvince': 'จังหวัดเลขทะเบียน',
  'vehicleInfoStep.selectProvince': 'เลือกจังหวัด',
  
  // Location/Area Autocomplete
  'autocomplete.noData': 'ไม่พบข้อมูล',
  'autocomplete.searchPlaceholder': 'ค้นหาอำเภอ/จังหวัด',
  'autocomplete.workArea': 'พื้นที่วิ่งงาน',
  'autocomplete.workAreaDesc': 'อำเภอ หรือ จังหวัด ที่ถนัดหรือวิ่งงานเป็นประจำ',
  'vehicleInfoStep.trailerPlateNumber': 'หมายเลขทะเบียนหางลาก (ไม่เว้นวรรคไม่ใส่ขีด)',
  'vehicleInfoStep.trailerPlateProvince': 'จังหวัดเลขทะเบียนหางลาก',
  'vehicleInfoStep.vehicleBrand': 'ยี่ห้อรถยนต์',
  'vehicleInfoStep.selectBrand': 'เลือกยี่ห้อ',
  'vehicleInfoStep.vehicleColor': 'สีรถยนต์',
  'vehicleInfoStep.vehicleColorPlaceholder': 'ระบุสีรถยนต์ (เช่น ขาว, น้ำเงิน)',
  'vehicleInfoStep.vin': 'VIN (หมายเลขประจำตัวยานพาหนะ)',
  'vehicleInfoStep.vehicleType': 'ประเภทรถยนต์',
  'vehicleInfoStep.selectType': 'เลือกประเภท',
  'vehicleInfoStep.fuelType': 'ประเภทเชื้อเพลิง',
  'vehicleInfoStep.selectFuel': 'เลือกเชื้อเพลิง',
  'vehicleInfoStep.loadCapacity': 'ความจุที่ได้รับ (กิโลกรัม)',
  'vehicleInfoStep.dimensions': 'ขนาดที่บรรทุกได้ (กว้างxยาวxสูง)',
  'vehicleInfoStep.width': 'กว้าง',
  'vehicleInfoStep.length': 'ยาว',
  'vehicleInfoStep.height': 'สูง',
  'vehicleInfoStep.containerTypes': 'สามารถรับประเภทตู้คอนเทนเนอร์',
  'vehicleInfoStep.container20': 'แบบสั้น 20\'',
  'vehicleInfoStep.container40': 'แบบยาว 40\'',
  'vehicleInfoStep.registrationDoc': 'รูปรายการจดทะเบียนรถ',
  'vehicleInfoStep.insuranceValue': 'มูลค่าประกันสินค้า (บาท)',
  'vehicleInfoStep.insuranceDoc': 'แนบเอกสารประกัน',
  'vehicleInfoStep.license': 'ใบอนุญาติขับขี่',
  'vehicleInfoStep.idCard': 'บัตรประชาชนผู้ขับ',
  'vehicleInfoStep.compulsoryInsurance': 'สำเนา พรบ.',
  'vehicleInfoStep.fileSelected': '✓ เลือกไฟล์แล้ว',
  'vehicleInfoStep.clickToTake': 'กดเพื่อถ่ายรูปหรือเลือกรูป',
  'vehicleInfoStep.addPhoto': 'เพิ่มรูปภาพ',
  'vehicleInfoStep.takePhoto': 'ถ่ายรูป',
  'vehicleInfoStep.selectFromGallery': 'เลือกจากแกลเลอรี',
  'vehicleInfoStep.back': 'ย้อนกลับ',
  'vehicleInfoStep.next': 'ต่อไป →',
  'vehicleInfoStep.cancel': 'ยกเลิก',
  
  // Review Step
  'review.generalInfo': 'ข้อมูลทั่วไป',
  'review.vehiclePhotos': 'อัพโหลดรูปรถ',
  'review.vehicleInfo': 'ข้อมูลรถ',
  'review.edit': 'แก้ไข',
  'review.personalInfo': 'ข้อมูลส่วนตัว',
  'review.firstName': 'ชื่อ',
  'review.lastName': 'นามสกุล',
  'review.phone': 'เบอร์โทรศัพท์',
  'review.email': 'อีเมล',
  'review.userInfo': 'ข้อมูลผู้ใช้งาน',
  'review.username': 'ชื่อผู้ใช้',
  'review.password': 'รหัสผ่าน',
  'review.workArea': 'พื้นที่วิ่งงาน',
  'review.workAreaLabel': 'อำเภอ หรือ จังหวัด ที่ถนัดหรือวิ่งงานเป็นประจำ',
  'review.priceRange': 'เรทราคาวิ่งงาน (฿)',
  'review.vehicleDetails': 'ข้อมูลรถยนต์',
  'review.plateNumber': 'หมายเลขทะเบียน',
  'review.plateProvince': 'จังหวัดเลขทะเบียน',
  'review.vehicleBrand': 'ยี่ห้อรถยนต์',
  'review.vehicleColor': 'สีรถยนต์',
  'review.vin': 'VIN',
  'review.vehicleType': 'ประเภทรถยนต์',
  'review.fuelType': 'ประเภทเชื้อเพลิง',
  'review.loadCapacity': 'ความจุที่ได้รับ (กิโลกรัม)',
  'review.dimensions': 'ขนาดที่บรรทุกได้',
  'review.containerTypes': 'ตู้คอนเทนเนอร์',
  'review.registrationDoc': 'รูปรายการจดทะเบียนรถ',
  'review.insuranceValue': 'มูลค่าประกันสินค้า',
  'review.insuranceDoc': 'แนบเอกสารประกัน',
  'review.licenseDoc': 'ใบอนุญาติขับขี่',
  'review.idCardDoc': 'บัตรประชาชนผู้ขับ',
  'review.compulsoryInsuranceDoc': 'สำเนา พรบ.',
  'review.noImage': 'ไม่พบรูปภาพ',
  'review.baht': 'บาท',
  'review.cancel': 'ยกเลิก',
  'review.createAccount': 'สร้างบัญชี',
  'review.failedTitle': 'ลงทะเบียนไม่สำเร็จ',
  'review.failedMessage': 'ขออภัย เกิดข้อผิดพลาดระหว่างการลงทะเบียน กรุณาตรวจสอบข้อมูลของคุณและลองอีกครั้ง',
  'review.tryAgain': 'ลองอีกครั้ง',
  
  // Pickup Detail Page
  'pickup.title': 'จุดรับสินค้า',
  'pickup.contactName': 'ชื่อผู้ติดต่อ',
  'pickup.routeNumber': 'เลขทาง',
  'pickup.address': 'ที่อยู่',
  'pickup.map': 'แผนที่',
  'pickup.productType': 'ประเภทสินค้า',
  'pickup.pickupTime': 'เข้ารับสินค้า',
  'pickup.note': 'หมายเหตุ',
  'pickup.call': 'โทร',
  'pickup.route': 'เส้นทาง',
  'pickup.checkIn': 'เช็คอิน',
  'pickup.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'pickup.confirmMessage': 'คุณต้องการเช็คอินที่ "จุดรับสินค้า Factory1" ใช่หรือไม่?',
  'pickup.cancel': 'ยกเลิก',
  'pickup.confirmButton': 'ยืนยัน',
  'pickup.checkInSuccess': 'เช็คอินสำเร็จ',
  'pickup.checkInSuccessMessage': 'คุณได้เช็คอินที่จุดรับสินค้าเรียบร้อยแล้ว',
  'pickup.error': 'เกิดข้อผิดพลาด',
  'pickup.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  'pickup.checkInError': 'ไม่สามารถบันทึกการเช็คอินได้',
  
  // Delivery Detail Page
  'delivery.title': 'จุดส่ง',
  'delivery.checkInSuccess': 'เช็คอินสำเร็จ',
  'delivery.paymentSuccess': 'ชำระเงินสำเร็จ',
  'delivery.paymentInfo': 'ข้อมูลการชำระเงิน',
  'delivery.paymentMethod': 'วิธีการชำระเงิน',
  'delivery.amount': 'จำนวนเงิน (บาท)',
  'delivery.cash': 'เงินสด',
  'delivery.mobileBanking': 'ชำระเงินผ่าน Mobile Banking',
  'delivery.qrCode': 'ชำระเงินผ่าน QR Code',
  'delivery.uploadDocument': 'อัพโหลดเอกสาร (ใบขนส่ง)',
  'delivery.clickToTake': 'กดเพื่อถ่ายหรือเลือก',
  'delivery.waybill': 'เอกสาร (ใบขนส่ง)',
  'delivery.podSuccess': 'POD สำเร็จ',
  'delivery.contactName': 'ชื่อผู้ติดต่อ',
  'delivery.routeNumber': 'เลขทาง',
  'delivery.address': 'ที่อยู่',
  'delivery.deliveryTime': 'เข้ารับสินค้า',
  'delivery.productType': 'ประเภทสินค้า',
  'delivery.note': 'หมายเหตุ',
  'delivery.call': 'โทร',
  'delivery.route': 'เส้นทาง',
  'delivery.checkIn': 'เช็คอิน',
  'delivery.payment': 'ชำระเงิน',
  'delivery.selectPaymentMethod': 'เลือกวิธีการชำระเงิน',
  'delivery.confirmPayment': 'ยืนยันการชำระเงิน',
  'delivery.confirmPaymentMessage': 'คุณต้องการยืนยันการชำระเงินใช่หรือไม่?',
  'delivery.paymentSuccessToast': 'บันทึกข้อมูลการชำระเงินเรียบร้อยแล้ว',
  'delivery.paymentError': 'ไม่สามารถบันทึกการชำระเงินได้',
  'delivery.podError': 'ไม่สามารถยืนยัน POD ได้',
  'delivery.podSuccessToast': 'บันทึกข้อมูล POD เรียบร้อยแล้ว',
  'delivery.uploadError': 'ไม่สามารถอัปโหลดเอกสารได้',
  'delivery.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'delivery.confirmMessage': 'คุณต้องการเช็คอินที่ "จุดส่ง หวค.ชัยน้ำตาล" ใช่หรือไม่?',
  'delivery.cancel': 'ยกเลิก',
  'delivery.confirmButton': 'ยืนยัน',
  
  // Container Check-in Page
  'container.title': 'จุดรับตู้เปล่า',
  'container.viewExpenses': 'ดูค่าใช้จ่าย',
  'container.addExpenses': 'เพิ่มค่าใช้จ่าย',
  'container.reportProblem': 'แจ้งปัญหา',
  'container.emptyContainerPoint': 'จุดรับตู้เปล่า',
  'container.startTime': 'วัน/เวลาเริ่มต้น',
  'container.checkpoint': 'วันรับเข้าช่างต้นต้น',
  'container.firstDatePickup': 'วันรับเข้าช่างต้นต้น (FIRST DATE PICK UP CTNR)',
  'container.pair': 'คู่ที่',
  'container.containerNo': 'เลขตู้คอนเทนเนอร์ (Container No.)',
  'container.sealNo': 'เลขซีล (Seal No.)',
  'container.route': 'เส้นทาง',
  'container.checkIn': 'เช็คอิน',
  'container.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'container.confirmMessage1': 'คุณต้องการเช็คอินที่',
  'container.confirmMessage2': 'ใช่หรือไม่?',
  'container.cancel': 'ยกเลิก',
  'container.confirm': 'ยืนยัน',
  'container.checkInSuccess': 'เช็คอินสำเร็จ',
  'container.checkInSuccessMessage': 'สถานะเปลี่ยนเป็น รอรับตู้เปล่า แล้ว',
  'container.checkInError': 'ไม่สามารถเช็คอินได้',
  'container.error': 'เกิดข้อผิดพลาด',
  'container.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  
  // SOP Check-in Page
  'sop.title': 'จุดรับสินค้า',
  'sop.checkInSuccess': 'เช็คอินสำเร็จ',
  'sop.uploadPhoto': 'อัพโหลดรูปสินค้า',
  'sop.clickToTake': 'กดเพื่อถ่ายหรือเลือก',
  'sop.productPhoto': 'รูปสินค้า',
  'sop.confirmSOP': 'ยืนยัน SOP',
  'sop.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'sop.confirmMessage': 'คุณต้องการยืนยันการยืนยันสินค้าด้วยไฟล์สแกน Scan of Package (SOP) ใช่หรือไม่?',
  'sop.cancel': 'ยกเลิก',
  'sop.confirm': 'ยืนยัน',
  'sop.saving': 'กำลังบันทึก...',
  'sop.photoRequired': 'กรุณาอัปโหลดรูปภาพ',
  'sop.photoRequiredMessage': 'คุณต้องอัปโหลดรูปสินค้าก่อนยืนยัน SOP',
  'sop.sopSuccess': 'ยืนยัน SOP สำเร็จ',
  'sop.sopSuccessMessage': 'บันทึกข้อมูลเรียบร้อยแล้ว',
  'sop.error': 'เกิดข้อผิดพลาด',
  'sop.errorMessage': 'ไม่สามารถบันทึกข้อมูลได้ กรุณาลองใหม่อีกครั้ง',
  'sop.selectSource': 'เลือกแหล่งที่มาของรูปภาพ',
  'sop.takePhoto': 'ถ่ายภาพ',
  'sop.selectFromGallery': 'เลือกรูปจากแกลอรี่',
  
  // Container SOP Page
  'containerSop.title': 'จุดรับตู้เปล่า',
  'containerSop.uploadPhoto': 'อัพโหลดรูปตู้เปล่า',
  'containerSop.clickToTake': 'คลิกเพื่อถ่ายหรือเลือกรูปตู้เปล่า',
  'containerSop.confirmButton': 'ยืนยันรับตู้เปล่า',
  'containerSop.confirmTitle': 'ยืนยันการรับตู้เปล่า',
  'containerSop.confirmMessage': 'คุณต้องการยืนยันการรับตู้เปล่าใช่หรือไม่?',
  'containerSop.photoRequiredMessage': 'กรุณาอัพโหลดรูปภาพตู้เปล่า',
  'containerSop.success': 'สำเร็จ',
  'containerSop.successMessage': 'บันทึกข้อมูลสำเร็จ',
  'containerSop.saveError': 'ไม่สามารถบันทึกข้อมูลได้',
  'containerSop.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  'containerSop.noData': 'ไม่พบข้อมูลงาน',
  'containerSop.loading': 'กำลังโหลด...',
  
  // Vehicle Info Page
  'vehicle.title': 'ข้อมูลรถ',
  'vehicle.dataTab': 'ข้อมูลรถ',
  'vehicle.photosTab': 'รูปรถ',
  'vehicle.registrationDoc': 'รูปรายการจดทะเบียนรถ',
  'vehicle.clickToView': 'กดที่นี่เพื่อดูรูป',
  'vehicle.plateNumber': 'หมายเลขทะเบียนรถ',
  'vehicle.plateProvince': 'จังหวัดจดทะเบียนรถ',
  'vehicle.brand': 'ยี่ห้อรถยนต์',
  'vehicle.color': 'สีรถยนต์',
  'vehicle.vin': 'VIN',
  'vehicle.type': 'ประเภทรถยนต์',
  'vehicle.fuelType': 'ประเภทเชื้อเพลิง',
  'vehicle.loadCapacity': 'น้ำหนักบรรทุก (ตัน)',
  'vehicle.containerTypes': 'ประเภทตู้คอนเทนเนอร์ที่รับงาน',
  'vehicle.hasTrailer': 'มีหางโครงคู่',
  'vehicle.trailerPlateNumber': 'หมายเลขทะเบียนหางโครงคู่',
  'vehicle.trailerPlateProvince': 'จังหวัดจดทะเบียนหางโครงคู่',
  'vehicle.dimensions': 'ขนาดรถบรรทุก',
  'vehicle.width': 'กว้าง (ม.)',
  'vehicle.length': 'ยาว (ม.)',
  'vehicle.height': 'สูง (ม.)',
  'vehicle.errorLoad': 'เกิดข้อผิดพลาด',
  'vehicle.errorLoadDesc': 'ไม่สามารถโหลดข้อมูลรถได้',
  'vehicle.uploadSuccess': 'อัพโหลดสำเร็จ',
  'vehicle.uploadSuccessDesc': 'รูปภาพถูกบันทึกเรียบร้อยแล้ว',
  'vehicle.uploadError': 'ไม่สามารถอัพโหลดรูปภาพได้',
  'vehicle.registrationSuccessDesc': 'รูปทะเบียนรถถูกบันทึกเรียบร้อยแล้ว',
  'vehicle.loading': 'กำลังโหลด...',
  'vehicle.noData': 'ไม่พบข้อมูลรถ',
  'vehicle.frontPhoto': 'รูปรถด้านหน้า',
  'vehicle.backPhoto': 'รูปรถด้านหลัง',
  'vehicle.leftPhoto': 'รูปรถด้านซ้าย',
  'vehicle.rightPhoto': 'รูปรถด้านขวา',
  'vehicle.selectPhoto': 'เลือกรูปภาพ',
  'vehicle.takePhoto': 'ถ่ายภาพ',
  'vehicle.chooseFromGallery': 'เลือกจากแกลอรี่',
  'vehicle.cancel': 'ยกเลิก',
  
  // Add Expense Page
  'expense.title': 'เพิ่มค่าใช้จ่าย',
  'expense.expense': 'ค่าใช้จ่าย',
  'expense.type': 'ประเภทค่าใช้จ่าย',
  'expense.typeRequired': '(ต้องกรอก)',
  'expense.price': 'ราคา',
  'expense.uploadReceipt': 'อัพโหลดรูปใบเสร็จ',
  'expense.clickToTake': 'กดเพื่อถ่ายหรือเลือก',
  'expense.receiptPhoto': 'รูปภาพใบเสร็จ',
  'expense.addMore': 'เพิ่มค่าใช้จ่าย',
  'expense.submitButton': 'เพิ่มค่าใช้จ่าย',
  'expense.confirmTitle': 'ยืนยันการเพิ่มค่าใช้จ่าย',
  'expense.totalAmount': 'ค่าใช้จ่ายทั้งหมด',
  'expense.baht': 'บาท',
  'expense.checkDetails': 'กรุณาตรวจสอบรายละเอียดและเอียดก่อนดำเนินการ',
  'expense.cancel': 'ยกเลิก',
  'expense.confirm': 'ยืนยัน',
  'expense.saving': 'กำลังบันทึก...',
  'expense.fillAllFields': 'กรุณากรอกข้อมูลให้ครบถ้วน',
  'expense.fillAllFieldsDesc': 'กรุณาเลือกประเภท กรอกราคา และอัพโหลดรูปใบเสร็จ',
  'expense.success': 'เพิ่มค่าใช้จ่ายสำเร็จ',
  'expense.successDesc': 'บันทึกค่าใช้จ่ายทั้งหมด',
  'expense.error': 'เกิดข้อผิดพลาด',
  'expense.errorDesc': 'ไม่สามารถบันทึกค่าใช้จ่ายได้',
  'expense.tollFee': 'ค่าทางด่วน',
  'expense.portFee': 'ค่าเข้าท่าเรือ',
  'expense.parkingFee': 'ค่าที่จอด',
  
  // Delivery Detail Page - Additional Keys
  'delivery.deliveryTo': 'ส่งของถึง',
  'delivery.employerName': 'หวค.ชัยน้ำตาล',
  'delivery.podCompleted': 'POD สำเร็จ',
  'delivery.contactPersonData': 'คุณธงใบย',
  'delivery.routeData': 'SAM001 เมือง/สมุทรปราการ',
  'delivery.addressData': 'ที่อยู่ 55/5 ช.ลาดพร้าว 101 แขวงคลองจั่น คณ.',
  'delivery.map': 'แผนที่',
  'delivery.productData': 'น้ำตาล (10 กล่อง)',
  'delivery.pickupTime': 'เข้ารับสินค้า',
  'delivery.remarks': 'หมายเหตุ',
  'delivery.navigate': 'เส้นทาง',
  'delivery.makePayment': 'ชำระเงิน',
  'delivery.confirmPod': 'ยืนยัน POD',
  'delivery.confirmStatusTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'delivery.confirmCheckInMessage': 'คุณต้องการเช็คอินที่ "จุดส่ง หวค.ชัยน้ำตาล" ใช่หรือไม่?',
  'delivery.confirm': 'ยืนยัน',
  'delivery.paymentChannel': 'ช่องทางชำระเงิน',
  'delivery.confirmPodMessage': 'คุณต้องการยืนยันการยืนยันอัพโหลดรูปสินค้า POD ใช่หรือไม่?',
  
  // Pickup Summary Page
  'pickupSummary.title': 'จุดรับสินค้า Factory1',
  'pickupSummary.error': 'เกิดข้อผิดพลาด',
  'pickupSummary.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  'pickupSummary.checkInSuccess': 'เช็คอินสำเร็จ',
  'pickupSummary.sopSuccess': 'SOP สำเร็จ',
  'pickupSummary.productPhoto': 'รูปภาพสินค้า',
  
  // Container Summary Page
  'containerSummary.error': 'เกิดข้อผิดพลาด',
  'containerSummary.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  'containerSummary.checkInSuccess': 'เช็คอินสำเร็จ',
  'containerSummary.containerSuccess': 'รับตู้เปล่าสำเร็จ',
  'containerSummary.containerPhoto': 'รูปภาพตู้เปล่า',
  
  // Delivery SOP Page
  'deliverySop.error': 'เกิดข้อผิดพลาด',
  'deliverySop.loadError': 'ไม่สามารถโหลดข้อมูลงานได้',
  'deliverySop.title': 'จุดส่ง คศน.ชัยนาท',
  'deliverySop.checkInSuccess': 'เช็คอินสำเร็จ',
  'deliverySop.uploadPhoto': 'อัพโหลดรูปสินค้า',
  'deliverySop.clickToTake': 'กดเพื่อถ่ายหรือเลือก<br />รูปสินค้า',
  'deliverySop.confirmSOP': 'ยืนยัน SOP',
  'deliverySop.photoRequired': 'กรุณาอัปโหลดรูปภาพ',
  'deliverySop.photoRequiredMessage': 'คุณต้องอัปโหลดรูปสินค้าก่อนยืนยัน SOP',
  'deliverySop.sopSuccess': 'ยืนยัน SOP สำเร็จ',
  'deliverySop.sopSuccessMessage': 'บันทึกข้อมูลเรียบร้อยแล้ว',
  'deliverySop.saveError': 'ไม่สามารถบันทึกข้อมูลได้ กรุณาลองใหม่อีกครั้ง',
  'deliverySop.confirmTitle': 'แจ้งเตือนการยืนยันสถานะ',
  'deliverySop.confirmMessage': 'คุณต้องการยืนยันการยืนยันสินค้าด้วยไฟล์สแกน<br />Scan of Package (SOP) ใช่หรือไม่?',
  'deliverySop.cancel': 'ยกเลิก',
  'deliverySop.confirm': 'ยืนยัน',
  'deliverySop.saving': 'กำลังบันทึก...',
  'deliverySop.selectSource': 'เลือกแหล่งที่มาของรูปภาพ',
  'deliverySop.takePhoto': 'ถ่ายภาพ',
  'deliverySop.selectFromGallery': 'เลือกรูปจากแกลอรี่',
  
  // Change Password Page
  'changePassword.title': 'เปลี่ยนรหัสผ่าน',
  'changePassword.newPassword': 'รหัสผ่านใหม่',
  'changePassword.confirmPassword': 'ยืนยันรหัสผ่าน',
  'changePassword.passwordMatch': 'รหัสผ่านตรงกันแล้ว',
  'changePassword.passwordMismatch': 'รหัสผ่านไม่ตรงกัน',
  'changePassword.usePassword': 'ใช้รหัสผ่านนี้',
  'changePassword.changing': 'กำลังเปลี่ยนรหัสผ่าน...',
  'changePassword.success': 'เปลี่ยนรหัสผ่านสำเร็จ',
  'changePassword.successDesc': 'กรุณาเข้าสู่ระบบด้วยรหัสผ่านใหม่',
  'changePassword.error': 'เกิดข้อผิดพลาด',
  'changePassword.errorDesc': 'ไม่สามารถเปลี่ยนรหัสผ่านได้',
  'changePassword.invalidData': 'ข้อมูลไม่ถูกต้อง',
  'changePassword.minLength': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
  
  // Forgot Password Page
  'forgotPassword.title': 'ลืมรหัสผ่าน?',
  'forgotPassword.subtitle': 'กรอกเบอร์โทรศัพท์ที่ลงทะเบียนไว้',
  'forgotPassword.phone': 'เบอร์โทรศัพท์',
  'forgotPassword.phonePlaceholder': '081 234 5679',
  'forgotPassword.phoneFormat': 'กรุณากรอกเบอร์โทรศัพท์ 10 หลัก',
  'forgotPassword.confirmButton': 'ยืนยัน',
  'forgotPassword.signInButton': 'เข้าสู่ระบบ',
  'forgotPassword.backButton': 'ย้อนกลับ',
  'forgotPassword.phoneVerified': 'ยืนยันเบอร์โทรศัพท์',
  'forgotPassword.phoneVerifiedDesc': 'กรุณาสร้างรหัสผ่านใหม่',
  'forgotPassword.error': 'เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง',
};

// English translations
const enTranslations: Record<string, string> = {
  // Settings Page
  'settings.title': 'Settings',
  'settings.profile': 'Profile',
  'settings.personal_info': 'Personal Information',
  'settings.account': 'Account',
  'settings.vehicle_info': 'Vehicle Information',
  'settings.general': 'General',
  'settings.notifications': 'Notifications',
  'settings.notifications_enabled': 'Notifications On',
  'settings.notifications_disabled': 'Notifications Off',
  'settings.about': 'About App',
  'settings.language': 'Language',
  'settings.terms': 'Terms of Service and Policy',
  'settings.contact': 'Contact Center',
  'settings.sign_out': 'Sign Out',
  'settings.sign_out_confirm': 'Do you want to sign out?',
  'settings.sign_out_description': 'Signing out will require you to log in again next time. Please confirm sign out.',
  'settings.cancel': 'Cancel',
  
  // Language Page
  'language.title': 'Language',
  'language.thai': 'ภาษาไทย',
  'language.english': 'English',
  
  // Bottom Navigation
  'nav.home': 'Home',
  'nav.dashboard': 'Dashboard',
  'nav.chat': 'Chat',
  'nav.settings': 'Settings',
  
  // Home Page
  'home.search': 'Search',
  'home.recommended': 'Recommended Jobs for You',
  'home.items': 'items',
  'home.error_load': 'Error',
  'home.error_load_desc': 'Unable to load jobs',
  'home.error_accept': 'Unable to accept job',
  'home.accept_success': 'Job Accepted',
  'home.accept_success_desc': 'You have accepted job',
  'home.greeting': '👋',
  'home.sunday': 'Sunday',
  'home.monday': 'Monday',
  'home.tuesday': 'Tuesday',
  'home.wednesday': 'Wednesday',
  'home.thursday': 'Thursday',
  'home.friday': 'Friday',
  'home.saturday': 'Saturday',
  'home.current_jobs': 'Current Jobs',
  'home.bidding': 'Bidding',
  'home.income': 'Income',
  'home.job_history': 'Job History',
  'home.sign_out_confirm': 'Do you want to sign out?',
  'home.sign_out_desc': 'Signing out will require you to log in again next time. Please confirm sign out.',
  'home.sign_out_btn': 'Sign Out',
  'home.cancel': 'Cancel',
  
  // Job Card
  'job.order_code': 'Order Code',
  'job.employer': 'Employer',
  'job.domestic': 'Domestic Transport',
  'job.international': 'International Transport',
  'job.inbound': 'Inbound',
  'job.outbound': 'Outbound',
  'job.origin': 'Origin',
  'job.destination': 'Destination',
  'job.equipment': 'Vehicle Equipment',
  'job.safety': 'Safety Equipment',
  'job.accept': 'Accept Job',
  'job.accepted': 'Job Accepted',
  
  // Confirm Job Dialog
  'confirm.title': 'Confirm Job Acceptance',
  'confirm.order_code': 'Order Code',
  'confirm.employer': 'Employer',
  'confirm.message': 'If you want to accept this job, please "Confirm"',
  'confirm.cancel': 'Cancel',
  'confirm.confirm': 'Confirm',
  
  // Job History Page
  'jobHistory.title': 'Job History',
  'jobHistory.all': 'All',
  'jobHistory.inProgress': 'In Progress',
  'jobHistory.completed': 'Completed',
  'jobHistory.selectMonth': 'Select Month',
  'jobHistory.allMonths': 'All Months',
  'jobHistory.january': 'January',
  'jobHistory.february': 'February',
  'jobHistory.march': 'March',
  'jobHistory.april': 'April',
  'jobHistory.may': 'May',
  'jobHistory.june': 'June',
  'jobHistory.july': 'July',
  'jobHistory.august': 'August',
  'jobHistory.september': 'September',
  'jobHistory.october': 'October',
  'jobHistory.november': 'November',
  'jobHistory.december': 'December',
  'jobHistory.loading': 'Loading...',
  'jobHistory.noData': 'No job history found',
  'jobHistory.statusCompleted': 'Completed',
  'jobHistory.statusDelivering': 'In Delivery',
  'jobHistory.statusAccepted': 'Accepted',
  
  // Current Jobs Page
  'currentJobs.title': 'Current Jobs',
  'currentJobs.search': 'Search by name, order, order code',
  'currentJobs.empty': 'No jobs available at the moment',
  'currentJobs.viewDetails': 'View Job Details',
  'currentJobs.filter': 'Filter',
  'currentJobs.dateRange': 'Job Assignment Date',
  'currentJobs.startDate': 'Start Date',
  'currentJobs.endDate': 'End Date',
  'currentJobs.clearFilter': 'Clear',
  'currentJobs.applyFilter': 'Search',
  'currentJobs.startJobDate': 'Start Date',
  'currentJobs.errorLoad': 'Error',
  'currentJobs.errorLoadDesc': 'Unable to load jobs',
  
  // Bidding Page
  'bidding.title': 'Bidding',
  'bidding.biddingTab': 'Bidding',
  'bidding.historyTab': 'History',
  'bidding.noJobs': 'No jobs available for bidding',
  'bidding.placeBid': 'Place Bid',
  'bidding.noHistory': 'No bidding history yet',
  'bidding.bidAt': 'Bid placed at',
  'bidding.statusPending': 'Pending',
  'bidding.statusAccepted': 'Completed',
  'bidding.statusRejected': 'Rejected',
  'bidding.monthLabel': 'February',
  
  // Income Page
  'income.title': 'My Income',
  'income.all': 'All',
  'income.paid': 'Paid',
  'income.unpaid': 'Unpaid',
  'income.selectMonth': 'Select Month',
  'income.viewDetails': 'View Job Details',
  'income.noData': 'No income data',
  'income.noPaid': 'No paid jobs',
  'income.noUnpaid': 'No unpaid jobs',
  'income.errorLoad': 'Error',
  'income.errorLoadDesc': 'Unable to load income data',
  
  // Dashboard Page
  'dashboard.finance': 'Finance (Expenses)',
  'dashboard.finance_desc': 'Track income and expenses easily',
  'dashboard.shipping': 'Shipping',
  'dashboard.shipping_desc': 'Check your shipments',
  'dashboard.customer': 'Customer',
  'dashboard.customer_desc': 'View your customer information',
  'dashboard.product': 'Product',
  'dashboard.product_desc': 'View product type information',
  'dashboard.view': 'View',

  // Finance Page
  'finance.title': 'Finance',
  'finance.day': 'Day',
  'finance.month': 'Month',
  'finance.year': 'Year',
  'finance.profit': 'Profit',
  'finance.expenses': 'Expenses',
  'finance.total_income': 'Total Income',
  'finance.compare_year': 'Compared to year: 2023',
  'finance.buddhist_era': 'Year',
  'finance.income': 'Income',
  'finance.pending_payments': 'Pending Payments',
  'finance.companies': 'Companies',

  // Shipping Page
  'shipping.title': 'Shipping',
  'shipping.all_types': 'All Transport Types',
  'shipping.tractor': 'Tractor',
  'shipping.12wheels': '12 Wheels',
  'shipping.10wheels': '10 Wheels',
  'shipping.6wheels': '6 Wheels',
  'shipping.4wheels': '4 Wheels',
  'shipping.job_data': 'Shipping Jobs Data',
  'shipping.all_jobs': 'All Jobs',
  'shipping.success': 'Success',
  'shipping.in_delivery': 'In Delivery',
  'shipping.cancelled': 'Cancelled',
  'shipping.by_region': 'Shipping by Region',
  'shipping.north': 'North',
  'shipping.central': 'Central',
  'shipping.northeast': 'Northeast',
  'shipping.east': 'East',
  'shipping.west': 'West',
  'shipping.south': 'South',

  // Customer Page
  'customer.title': 'Customer',
  'customer.top_5': 'Top 5',
  'customer.jobs': 'jobs',

  // Product Page
  'product.title': 'Product',
  'product.product_types': 'Product Types',
  'product.top_5': 'Top 5',
  'product.jobs': 'jobs',
  
  // Search Page
  'search.title': 'Search',
  'search.search': 'Search',
  'search.results': 'Search Results',
  'search.no_results': 'No results found',
  'search.recent': 'Recent Searches',
  'search.popular': 'Popular Searches',
  'search.filter': 'Filter',
  'search.filter_desc': 'Filter search results',
  'search.domestic': 'Domestic Transport',
  'search.international': 'International Transport',
  'search.province': 'Province',
  'search.district': 'District',
  'search.select_province': 'Select Province',
  'search.select_district': 'Select District',
  'search.select_district_first': 'Please select province first',
  'search.price_range': 'Price Range (฿)',
  'search.min_price': 'Enter minimum price',
  'search.max_price': 'Enter maximum price',
  'search.clear': 'Clear',
  'search.apply': 'Search',
  
  // Profile Page
  'profile.title': 'Profile',
  'profile.first_name': 'First Name',
  'profile.last_name': 'Last Name',
  'profile.phone': 'Phone Number',
  'profile.email': 'Email',
  'profile.work_areas': 'Districts or provinces you work regularly',
  'profile.price_range': 'Job Price Range (฿)',
  'profile.change_avatar': 'Confirm Profile Picture Change',
  'profile.change_avatar_desc': 'Do you want to change your profile picture to this one?',
  'profile.confirm': 'Confirm',
  'profile.cancel': 'Cancel',
  'profile.uploading': 'Uploading...',
  'profile.error_upload': 'Unable to upload image',
  'profile.error_update': 'Unable to update profile',
  'profile.success': 'Success',
  'profile.success_desc': 'Profile picture updated',
  
  // Account Page
  'account.title': 'Account',
  'account.username': 'Username',
  'account.no_data': 'No data',
  'account.password': 'Password',
  'account.delete': 'Delete Account',
  'account.delete_confirm': 'Are you sure you want to delete your account?',
  'account.delete_desc': 'Deleting this account will remove all data',
  'account.delete_personal': 'Personal information',
  'account.delete_history': 'Service history',
  'account.delete_transactions': 'All transaction data',
  'account.delete_warning': 'Account deletion cannot be undone',
  'account.deleting': 'Deleting...',
  'account.cancel': 'Cancel',
  'account.delete_success': 'Account Deleted Successfully',
  'account.delete_success_desc': 'Your account has been deleted',
  'account.delete_error': 'Error',
  'account.delete_error_desc': 'Unable to delete account. Please try again.',
  
  // Terms Page
  'terms.title': 'Terms of Service and Policy',
  'terms.heading': 'Truckers  Privacy Policy for Drivers',
  'terms.updated_date': 'Effective as of January 15, 2024',
  'terms.collection_title': 'Data We Collect',
  'terms.collection_intro': 'We collect information necessary to provide the Truckers app services to drivers. This includes information you provide directly and information we collect from your use of the app, such as:',
  'terms.personal_data': 'Personal Data:',
  'terms.personal_data_desc': 'Such as name, email, phone number, and account information related to transportation',
  'terms.technical_data': 'Technical Data:',
  'terms.technical_data_desc': 'Including trip data, location (GPS), speed, route selection, start and end times of transportation',
  'terms.price_data': 'Price Data:',
  'terms.price_data_desc': 'Including vehicle registration number, vehicle type, and information related to truck condition',
  'terms.financial_data': 'Financial Data:',
  'terms.financial_data_desc': 'Data used for payment such as bank account details or credit card information',
  'terms.communication_data': 'Communication Data:',
  'terms.communication_data_desc': 'Messages, conversations, or communications through the app related to service provision',
  'terms.usage_title': 'How We Use Data',
  'terms.usage_intro': 'We will use your data in various ways, such as:',
  'terms.usage_1': 'Processing transportation request submissions',
  'terms.usage_2': 'Calculating service fees and payment',
  'terms.usage_3': 'Improving service provision and app development',
  'terms.usage_4': 'Contacting you to provide information about transportation status or notifications',
  'terms.usage_5': 'Improving your user experience',
  'terms.usage_6': 'Complying with legal requirements',
  'terms.sharing_title': 'Data Sharing',
  
  // Job Detail Page
  'jobDetail.error': 'Error',
  'jobDetail.errorLoadDesc': 'Unable to load job data',
  'jobDetail.notFound': 'Job not found',
  'jobDetail.invalidType': 'Invalid job type',
  'jobDetail.domestic': 'Domestic Transport',
  'jobDetail.international': 'International Transport',
  'jobDetail.inbound': 'Inbound',
  'jobDetail.outbound': 'Outbound',
  'jobDetail.reportProblem': 'Report Problem',
  'jobDetail.booking': 'Booking',
  'jobDetail.employer': 'Employer',
  'jobDetail.pickupPoint': 'Pickup Point',
  'jobDetail.deliveryPoint': 'Delivery Point',
  'jobDetail.sopSuccess': 'SOP Complete',
  'jobDetail.waitingSop': 'Waiting SOP',
  'jobDetail.waitingCheckIn': 'Waiting Check-in',
  'jobDetail.podSuccess': 'POD Complete',
  'jobDetail.waitingPod': 'Waiting POD',
  'jobDetail.contactPerson': 'Contact Person',
  'jobDetail.position': 'Position',
  'jobDetail.goodsType': 'Goods Type',
  'jobDetail.pickupTime': 'Pickup Time',
  'jobDetail.deliveryTime': 'Delivery Time',
  'jobDetail.remarks': 'Remarks',
  'jobDetail.call': 'Call',
  'jobDetail.route': 'Route',
  'jobDetail.viewInfo': 'View Info',
  'jobDetail.updateStatus': 'Update Status',
  'jobDetail.startJob': 'Start Job',
  'jobDetail.startJobNow': 'Start Job Now',
  'jobDetail.pickupDeliveryPoints': 'Pickup/Delivery Points',
  'jobDetail.errorStartJob': 'Unable to start job',
  'jobDetail.startJobSuccess': 'Job Started Successfully',
  'jobDetail.startJobSuccessDesc': 'You can now proceed with delivery',
  'jobDetail.containerCheckpoint': 'Empty Container Pickup',
  'jobDetail.containerSuccess': 'Container Pickup Complete',
  'jobDetail.waitingContainer': 'Waiting Container',
  'jobDetail.startDateTime': 'Start Date/Time',
  'jobDetail.emptyContainerDate': 'Empty Container Date',
  'jobDetail.receiver': 'Receiver',
  'jobDetail.containerDate': 'Container Date',
  'jobDetail.containerNumber': 'Container Number',
  'jobDetail.sealNumber': 'Seal Number',
  'jobDetail.loadingPoint': 'Loading Point',
  'jobDetail.unloadingPoint': 'Unloading Point',
  'jobDetail.billOfLading': 'Bill of Lading',
  'jobDetail.contactPoint': 'Contact Point',
  'jobDetail.routeCode': 'Route Code',
  'jobDetail.deliveryRoute': 'Route',
  'jobDetail.emptyReturn': 'Empty Return Point',
  'jobDetail.fullReturn': 'Full Return Point',
  'jobDetail.returnDeadline': 'Return Deadline',
  'jobDetail.guarantor': 'Guarantor',
  'jobDetail.returnDate': 'Return Date',
  'jobDetail.startJobDesc': 'You can now start container inspection',
  'terms.sharing_intro': 'We will not share your personal data with third parties, except in the following cases:',
  'terms.sharing_provider': 'Service Providers We Hire:',
  'terms.sharing_provider_desc': 'Companies or individuals we use for services in various areas (such as payment services, data analysis) that have privacy terms to protect your data',
  'terms.sharing_legal': 'Legal Compliance:',
  'terms.sharing_legal_desc': 'In cases where we are required by law, such as providing information to government agencies or complying with court orders',
  'terms.sharing_anonymous': 'Sharing of De-identified Data:',
  'terms.sharing_anonymous_desc': 'Such as anonymized statistical data or data used for analysis to improve the app',
  
  // Chat Page
  'chat.title': 'Chat',
  'chat.search': 'Search conversations',
  'chat.company': 'Company',
  'chat.friends': 'Friends',
  'chat.groups': 'Groups',
  'chat.online': 'Online',
  'chat.offline': 'Offline',
  'chat.typeMessage': 'Type a message',
  'chat.welcomeGroup': 'Welcome to the group chat with your friends!',
  'chat.addMembers': 'Add Members',
  'chat.memberList': 'Member List',
  'chat.filesMedia': 'Files and Media',
  'chat.muteNotifications': 'Mute Notifications',
  'chat.deleteConversation': 'Delete Conversation',
  'chat.error': 'Error',
  'chat.sendError': 'Failed to send message',
  'chat.muted': 'Muted',
  'chat.mutedDesc': 'You will no longer receive notifications from this conversation',
  'chat.createGroup': 'Create New Group',
  'chat.groupName': 'Group Name',
  'chat.groupNamePlaceholder': 'Enter group name',
  'chat.groupNameRequired': 'Please enter group name',
  'chat.selectMembers': 'Select Members',
  'chat.searchMembers': 'Search members...',
  'chat.selectMembersRequired': 'Please select at least 1 member',
  'chat.selectedCount': 'Selected',
  'chat.cancel': 'Cancel',
  'chat.create': 'Create',
  'chat.creating': 'Creating...',
  'chat.success': 'Success',
  'chat.groupCreated': '🎉 Group created',
  'chat.groupCreatedSuccess': 'Group created successfully',
  'chat.groupCreatedError': 'Failed to create group',
  'chat.noMembersFound': 'No members found',
  'chat.manageGroup': 'Manage Group',
  'chat.info': 'Info',
  'chat.members': 'Members',
  'chat.you': 'You',
  'chat.groupNameUpdated': 'Group name updated',
  'chat.updateError': 'Failed to update',
  'chat.membersAdded': 'Members added',
  'chat.addMembersError': 'Failed to add members',
  'chat.memberRemoved': 'Member removed',
  'chat.removeMemberError': 'Failed to remove member',
  'chat.cannotRemoveSelf': 'Cannot remove yourself from group',
  'chat.adding': 'Adding...',
  'chat.addSelected': 'Add Selected',

  // Report Problem Drawer
  'reportProblem.title': 'Report Problem',
  'reportProblem.problemAccident': 'Report Problem / Accident',
  'reportProblem.partialDelivery': 'Partial Delivery',
  'reportProblem.pauseWork': 'Pause Work',
  'reportProblem.reportIssue': 'Report Issue',
  'reportProblem.specifyTime': 'Specify Time',
  'reportProblem.specifyReason': 'Specify Reason',
  'reportProblem.reasonPlaceholder': 'Enter reason',
  'reportProblem.uploadPhoto': 'Upload Product Photo',
  'reportProblem.clickToTake': 'Click to take or select',
  'reportProblem.productPhoto': 'product photo',
  'reportProblem.fileSelected': 'File selected',
  'reportProblem.downloadVehicleChange': 'Download Vehicle Change Form',
  'reportProblem.confirm': 'Confirm',
  'reportProblem.fillAllFields': 'Please fill in all fields',
  
  // Job Action Buttons
  'jobActions.viewExpenses': 'View Expenses',
  'jobActions.addExpense': 'Add Expense',
  'jobActions.reportProblem': 'Report Problem',
  
  // Sign In Page
  'signIn.title': 'Sign In or Register',
  'signIn.username': 'Username',
  'signIn.password': 'Password',
  'signIn.rememberMe': 'Remember me',
  'signIn.forgotPassword': 'Forgot password?',
  'signIn.signInButton': 'Sign In',
  'signIn.registerButton': 'Register',
  'signIn.success': 'Sign in successful',
  'signIn.welcomeBack': 'Welcome back',
  'signIn.error': 'An error occurred. Please try again',
  'signIn.invalidCredentials': 'Invalid email or password. Please try again',
  'signIn.validation.emailRequired': 'Please enter username',
  'signIn.validation.emailFormat': 'Invalid email format',
  'signIn.validation.passwordMin': 'Password must be at least 8 characters',
  
  // Register Page
  'register.steps.terms': 'Terms of Service and Policy',
  'register.steps.generalInfo': 'General Information',
  'register.steps.vehiclePhotos': 'Upload Vehicle Photos',
  'register.steps.vehicleInfo': 'Vehicle Information',
  'register.steps.review': 'Review Information',
  'register.success': 'Registration successful!',
  'register.successDesc': 'Your information has been saved successfully',
  'register.error': 'An error occurred',
  'register.errorDesc': 'Please try again',
  'register.createAccountFailed': 'Failed to create account. Please try again',
  'register.createAccountError': 'Unable to create account',
  'register.vehicleSaveFailed': 'Failed to save vehicle information',
  
  // Terms Step (Register)
  'termsStep.title': 'Truckers Driver Privacy Policy',
  'termsStep.effectiveDate': 'Effective Date: January 15, 2024',
  'termsStep.accept': 'Accept',
  'termsStep.scrollToAccept': 'Scroll down to continue',
  'termsStep.scrollMessage': 'Please scroll through the terms to continue',
  
  // General Info Step
  'generalInfo.profilePhoto': 'Driver Photo',
  'generalInfo.selectPhoto': 'Select Photo',
  'generalInfo.takePhoto': 'Take Photo',
  'generalInfo.takePhotoDesc': 'Open camera to take photo',
  'generalInfo.selectFromGallery': 'Select from Gallery',
  'generalInfo.selectFromGalleryDesc': 'Select existing photo from device',
  'generalInfo.photoPrompt': 'Click to take or select photo',
  'generalInfo.personalInfo': 'Personal Information',
  'generalInfo.firstName': 'First Name (as per ID card)',
  'generalInfo.lastName': 'Last Name (as per ID card)',
  'generalInfo.phone': 'Phone Number',
  'generalInfo.email': 'Email',
  'generalInfo.userInfo': 'User Information',
  'generalInfo.username': 'Username',
  'generalInfo.password': 'Password',
  'generalInfo.confirmPassword': 'Confirm Password',
  'generalInfo.workArea': 'Work Area',
  'generalInfo.workAreaLabel': 'District or Province where you usually work',
  'generalInfo.workAreaPlaceholder': 'Search district/province',
  'generalInfo.priceRange': 'Job Rate (฿)',
  'generalInfo.priceMin': 'Enter minimum price',
  'generalInfo.priceMax': 'Enter maximum price',
  'generalInfo.next': 'Next →',
  'generalInfo.validation.firstNameRequired': 'Please enter first name',
  'generalInfo.validation.lastNameRequired': 'Please enter last name',
  'generalInfo.validation.phoneRequired': 'Please enter valid phone number',
  'generalInfo.validation.emailFormat': 'Invalid email format',
  'generalInfo.validation.usernameRequired': 'Please enter username',
  'generalInfo.validation.passwordMin': 'Password must be at least 8 characters',
  'generalInfo.validation.confirmPasswordMin': 'Please confirm password',
  'generalInfo.validation.passwordMismatch': 'Passwords do not match',
  'generalInfo.validation.priceMinRequired': 'Please enter minimum price',
  'generalInfo.validation.priceMaxRequired': 'Please enter maximum price',
  'generalInfo.validation.priceRange': 'Please enter price range',
  
  // Vehicle Photos Step
  'vehiclePhotosStep.frontPhoto': 'Front Photo',
  'vehiclePhotosStep.sidePhoto': 'Side Photo',
  'vehiclePhotosStep.backPhoto': 'Back Photo',
  'vehiclePhotosStep.platePhoto': 'License Plate Photo',
  'vehiclePhotosStep.hasTrailer': 'Has Trailer',
  'vehiclePhotosStep.trailerPlatePhoto': 'Trailer License Plate Photo',
  'vehiclePhotosStep.clickToTake': 'Click to take or select photo',
  'vehiclePhotosStep.addPhoto': 'Add Photo',
  'vehiclePhotosStep.takePhoto': 'Take Photo',
  'vehiclePhotosStep.selectFromGallery': 'Select from Gallery',
  'vehiclePhotosStep.cancel': 'Cancel',
  'vehiclePhotosStep.back': 'Back',
  'vehiclePhotosStep.next': 'Next →',
  
  // Vehicle Info Step
  'vehicleInfoStep.plateNumber': 'License Plate Number (no spaces or dashes)',
  'vehicleInfoStep.plateProvince': 'License Plate Province',
  'vehicleInfoStep.selectProvince': 'Select province',
  
  // Location/Area Autocomplete
  'autocomplete.noData': 'No data found',
  'autocomplete.searchPlaceholder': 'Search district/province',
  'autocomplete.workArea': 'Work Area',
  'autocomplete.workAreaDesc': 'Districts or provinces you work regularly',
  'vehicleInfoStep.trailerPlateNumber': 'Trailer License Plate Number (no spaces or dashes)',
  'vehicleInfoStep.trailerPlateProvince': 'Trailer License Plate Province',
  'vehicleInfoStep.vehicleBrand': 'Vehicle Brand',
  'vehicleInfoStep.selectBrand': 'Select brand',
  'vehicleInfoStep.vehicleColor': 'Vehicle Color',
  'vehicleInfoStep.vehicleColorPlaceholder': 'Specify vehicle color (e.g. white, blue)',
  'vehicleInfoStep.vin': 'VIN (Vehicle Identification Number)',
  'vehicleInfoStep.vehicleType': 'Vehicle Type',
  'vehicleInfoStep.selectType': 'Select type',
  'vehicleInfoStep.fuelType': 'Fuel Type',
  'vehicleInfoStep.selectFuel': 'Select fuel',
  'vehicleInfoStep.loadCapacity': 'Load Capacity (kilograms)',
  'vehicleInfoStep.dimensions': 'Load Dimensions (width x length x height)',
  'vehicleInfoStep.width': 'Width',
  'vehicleInfoStep.length': 'Length',
  'vehicleInfoStep.height': 'Height',
  'vehicleInfoStep.containerTypes': 'Container Types Accepted',
  'vehicleInfoStep.container20': 'Short 20\'',
  'vehicleInfoStep.container40': 'Long 40\'',
  'vehicleInfoStep.registrationDoc': 'Vehicle Registration Document',
  'vehicleInfoStep.insuranceValue': 'Insurance Value (Baht)',
  'vehicleInfoStep.insuranceDoc': 'Insurance Document',
  'vehicleInfoStep.license': 'Driver\'s License',
  'vehicleInfoStep.idCard': 'Driver\'s ID Card',
  'vehicleInfoStep.compulsoryInsurance': 'Compulsory Insurance Copy',
  'vehicleInfoStep.fileSelected': '✓ File Selected',
  'vehicleInfoStep.clickToTake': 'Click to take or select photo',
  'vehicleInfoStep.addPhoto': 'Add Photo',
  'vehicleInfoStep.takePhoto': 'Take Photo',
  'vehicleInfoStep.selectFromGallery': 'Select from Gallery',
  'vehicleInfoStep.back': 'Back',
  'vehicleInfoStep.next': 'Next →',
  'vehicleInfoStep.cancel': 'Cancel',
  
  // Review Step
  'review.generalInfo': 'General Information',
  'review.vehiclePhotos': 'Vehicle Photos',
  'review.vehicleInfo': 'Vehicle Information',
  'review.edit': 'Edit',
  'review.personalInfo': 'Personal Information',
  'review.firstName': 'First Name',
  'review.lastName': 'Last Name',
  'review.phone': 'Phone Number',
  'review.email': 'Email',
  'review.userInfo': 'User Information',
  'review.username': 'Username',
  'review.password': 'Password',
  'review.workArea': 'Work Area',
  'review.workAreaLabel': 'District or Province where you usually work',
  'review.priceRange': 'Job Rate (฿)',
  'review.vehicleDetails': 'Vehicle Details',
  'review.plateNumber': 'License Plate Number',
  'review.plateProvince': 'License Plate Province',
  'review.vehicleBrand': 'Vehicle Brand',
  'review.vehicleColor': 'Vehicle Color',
  'review.vin': 'VIN',
  'review.vehicleType': 'Vehicle Type',
  'review.fuelType': 'Fuel Type',
  'review.loadCapacity': 'Load Capacity (kilograms)',
  'review.dimensions': 'Load Dimensions',
  'review.containerTypes': 'Container Types',
  'review.registrationDoc': 'Vehicle Registration Document',
  'review.insuranceValue': 'Insurance Value',
  'review.insuranceDoc': 'Insurance Document',
  'review.licenseDoc': 'Driver\'s License',
  'review.idCardDoc': 'Driver\'s ID Card',
  'review.compulsoryInsuranceDoc': 'Compulsory Insurance Copy',
  'review.noImage': 'No image found',
  'review.baht': 'Baht',
  'review.cancel': 'Cancel',
  'review.createAccount': 'Create Account',
  'review.failedTitle': 'Registration Failed',
  'review.failedMessage': 'Sorry, an error occurred during registration. Please check your information and try again',
  'review.tryAgain': 'Try Again',
  
  // Pickup Detail Page
  'pickup.title': 'Pickup Point',
  'pickup.contactName': 'Contact Name',
  'pickup.routeNumber': 'Route Number',
  'pickup.address': 'Address',
  'pickup.map': 'Map',
  'pickup.productType': 'Product Type',
  'pickup.pickupTime': 'Pickup Time',
  'pickup.note': 'Note',
  'pickup.call': 'Call',
  'pickup.route': 'Route',
  'pickup.checkIn': 'Check In',
  'pickup.confirmTitle': 'Confirm Status',
  'pickup.confirmMessage': 'Do you want to check in at "Pickup Point Factory1"?',
  'pickup.cancel': 'Cancel',
  'pickup.confirmButton': 'Confirm',
  'pickup.checkInSuccess': 'Check-in Successful',
  'pickup.checkInSuccessMessage': 'You have checked in at the pickup point',
  'pickup.error': 'Error',
  'pickup.loadError': 'Unable to load job data',
  'pickup.checkInError': 'Unable to save check-in',
  
  // Delivery Detail Page
  'delivery.title': 'Delivery Point',
  'delivery.checkInSuccess': 'Check-in Successful',
  'delivery.paymentSuccess': 'Payment Successful',
  'delivery.paymentInfo': 'Payment Information',
  'delivery.paymentMethod': 'Payment Method',
  'delivery.amount': 'Amount (Baht)',
  'delivery.cash': 'Cash',
  'delivery.mobileBanking': 'Mobile Banking',
  'delivery.qrCode': 'QR Code',
  'delivery.uploadDocument': 'Upload Document (Waybill)',
  'delivery.clickToTake': 'Click to take or select',
  'delivery.waybill': 'document (waybill)',
  'delivery.podSuccess': 'POD Successful',
  'delivery.contactName': 'Contact Name',
  'delivery.routeNumber': 'Route Number',
  'delivery.address': 'Address',
  'delivery.deliveryTime': 'Delivery Time',
  'delivery.productType': 'Product Type',
  'delivery.note': 'Note',
  'delivery.call': 'Call',
  'delivery.route': 'Route',
  'delivery.checkIn': 'Check In',
  'delivery.payment': 'Payment',
  'delivery.selectPaymentMethod': 'Select Payment Method',
  'delivery.confirmPayment': 'Confirm Payment',
  'delivery.confirmPaymentMessage': 'Do you want to confirm the payment?',
  'delivery.paymentSuccessToast': 'Payment information saved successfully',
  'delivery.paymentError': 'Unable to save payment',
  'delivery.podError': 'Unable to confirm POD',
  'delivery.podSuccessToast': 'POD information saved successfully',
  'delivery.uploadError': 'Unable to upload document',
  'delivery.confirmTitle': 'Confirm Status',
  'delivery.confirmMessage': 'Do you want to check in at "Delivery Point Chai Sugar"?',
  'delivery.cancel': 'Cancel',
  'delivery.confirmButton': 'Confirm',
  
  // Delivery Detail Page - Additional Keys
  'delivery.deliveryTo': 'Delivery To',
  'delivery.employerName': 'Chai Sugar Company',
  'delivery.podCompleted': 'POD Completed',
  'delivery.contactPersonData': 'Mr. Thongbai',
  'delivery.routeData': 'SAM001 Mueang/Samut Prakan',
  'delivery.addressData': 'Address 55/5 Ladprao 101 Rd., Khlong Chan, BKK',
  'delivery.map': 'Map',
  'delivery.productData': 'Sugar (10 boxes)',
  'delivery.pickupTime': 'Pickup Time',
  'delivery.remarks': 'Remarks',
  'delivery.navigate': 'Navigate',
  'delivery.makePayment': 'Make Payment',
  'delivery.confirmPod': 'Confirm POD',
  'delivery.confirmStatusTitle': 'Confirm Status',
  'delivery.confirmCheckInMessage': 'Do you want to check in at "Delivery Point Chai Sugar"?',
  'delivery.confirm': 'Confirm',
  'delivery.paymentChannel': 'Payment Method',
  'delivery.confirmPodMessage': 'Do you want to confirm uploading POD product photo?',
  
  // Pickup Summary Page
  'pickupSummary.title': 'Pickup Point Factory1',
  'pickupSummary.error': 'Error',
  'pickupSummary.loadError': 'Unable to load job data',
  'pickupSummary.checkInSuccess': 'Check-in Successful',
  'pickupSummary.sopSuccess': 'SOP Successful',
  'pickupSummary.productPhoto': 'Product Photo',
  
  // Container Summary Page
  'containerSummary.error': 'Error',
  'containerSummary.loadError': 'Unable to load job data',
  'containerSummary.checkInSuccess': 'Check-in Successful',
  'containerSummary.containerSuccess': 'Container Pickup Successful',
  'containerSummary.containerPhoto': 'Empty Container Photo',
  
  // Delivery SOP Page
  'deliverySop.error': 'Error',
  'deliverySop.loadError': 'Unable to load job data',
  'deliverySop.title': 'Delivery Point',
  'deliverySop.checkInSuccess': 'Check-in Successful',
  'deliverySop.uploadPhoto': 'Upload Product Photo',
  'deliverySop.clickToTake': 'Click to take or select<br />product photo',
  'deliverySop.confirmSOP': 'Confirm SOP',
  'deliverySop.photoRequired': 'Please upload photo',
  'deliverySop.photoRequiredMessage': 'You must upload product photo before confirming SOP',
  'deliverySop.sopSuccess': 'SOP Confirmed Successfully',
  'deliverySop.sopSuccessMessage': 'Data saved successfully',
  'deliverySop.saveError': 'Unable to save data. Please try again',
  'deliverySop.confirmTitle': 'Confirm Status',
  'deliverySop.confirmMessage': 'Do you want to confirm product with scan file<br />Scan of Package (SOP)?',
  'deliverySop.cancel': 'Cancel',
  'deliverySop.confirm': 'Confirm',
  'deliverySop.saving': 'Saving...',
  'deliverySop.selectSource': 'Select Photo Source',
  'deliverySop.takePhoto': 'Take Photo',
  'deliverySop.selectFromGallery': 'Select from Gallery',
  
  // Container Check-in Page
  'container.title': 'Empty Container Point',
  'container.viewExpenses': 'View Expenses',
  'container.addExpenses': 'Add Expenses',
  'container.reportProblem': 'Report Problem',
  'container.emptyContainerPoint': 'Empty Container Point',
  'container.startTime': 'Start Date/Time',
  'container.checkpoint': 'Checkpoint',
  'container.firstDatePickup': 'First Date Pick Up CTNR',
  'container.pair': 'Pair',
  'container.containerNo': 'Container No.',
  'container.sealNo': 'Seal No.',
  'container.route': 'Route',
  'container.checkIn': 'Check In',
  'container.confirmTitle': 'Confirm Status',
  'container.confirmMessage1': 'Do you want to check in at',
  'container.confirmMessage2': '?',
  'container.cancel': 'Cancel',
  'container.confirm': 'Confirm',
  'container.checkInSuccess': 'Check-in Successful',
  'container.checkInSuccessMessage': 'Status changed to waiting for empty container',
  'container.checkInError': 'Unable to check in',
  'container.error': 'Error',
  'container.loadError': 'Unable to load job data',
  
  // SOP Check-in Page
  'sop.title': 'Pickup Point',
  'sop.checkInSuccess': 'Check-in Successful',
  'sop.uploadPhoto': 'Upload Product Photo',
  'sop.clickToTake': 'Click to take or select',
  'sop.productPhoto': 'product photo',
  'sop.confirmSOP': 'Confirm SOP',
  'sop.confirmTitle': 'Confirm Status',
  'sop.confirmMessage': 'Do you want to confirm the product with Scan of Package (SOP)?',
  'sop.cancel': 'Cancel',
  'sop.confirm': 'Confirm',
  'sop.saving': 'Saving...',
  'sop.photoRequired': 'Please upload a photo',
  'sop.photoRequiredMessage': 'You must upload a product photo before confirming SOP',
  'sop.sopSuccess': 'SOP Confirmed Successfully',
  'sop.sopSuccessMessage': 'Information saved successfully',
  'sop.error': 'Error',
  'sop.errorMessage': 'Unable to save information. Please try again',
  'sop.selectSource': 'Select Photo Source',
  'sop.takePhoto': 'Take Photo',
  'sop.selectFromGallery': 'Select from Gallery',
  
  // Container SOP Page
  'containerSop.title': 'Empty Container Point',
  'containerSop.uploadPhoto': 'Upload Empty Container Photo',
  'containerSop.clickToTake': 'Click to take or select empty container photo',
  'containerSop.confirmButton': 'Confirm Empty Container Receipt',
  'containerSop.confirmTitle': 'Confirm Empty Container Receipt',
  'containerSop.confirmMessage': 'Do you want to confirm receiving the empty container?',
  'containerSop.photoRequiredMessage': 'Please upload an empty container photo',
  'containerSop.success': 'Success',
  'containerSop.successMessage': 'Information saved successfully',
  'containerSop.saveError': 'Unable to save information',
  'containerSop.loadError': 'Unable to load job data',
  'containerSop.noData': 'Job data not found',
  'containerSop.loading': 'Loading...',
  
  // Vehicle Info Page
  'vehicle.title': 'Vehicle Information',
  'vehicle.dataTab': 'Vehicle Data',
  'vehicle.photosTab': 'Vehicle Photos',
  'vehicle.registrationDoc': 'Vehicle Registration Document',
  'vehicle.clickToView': 'Click here to view',
  'vehicle.plateNumber': 'Plate Number',
  'vehicle.plateProvince': 'Plate Province',
  'vehicle.brand': 'Vehicle Brand',
  'vehicle.color': 'Vehicle Color',
  'vehicle.vin': 'VIN',
  'vehicle.type': 'Vehicle Type',
  'vehicle.fuelType': 'Fuel Type',
  'vehicle.loadCapacity': 'Load Capacity (tons)',
  'vehicle.containerTypes': 'Container Types',
  'vehicle.hasTrailer': 'Has Trailer',
  'vehicle.trailerPlateNumber': 'Trailer Plate Number',
  'vehicle.trailerPlateProvince': 'Trailer Plate Province',
  'vehicle.dimensions': 'Truck Dimensions',
  'vehicle.width': 'Width (m.)',
  'vehicle.length': 'Length (m.)',
  'vehicle.height': 'Height (m.)',
  'vehicle.errorLoad': 'Error',
  'vehicle.errorLoadDesc': 'Unable to load vehicle data',
  'vehicle.uploadSuccess': 'Upload Successful',
  'vehicle.uploadSuccessDesc': 'Image saved successfully',
  'vehicle.uploadError': 'Unable to upload image',
  'vehicle.registrationSuccessDesc': 'Registration document saved successfully',
  'vehicle.loading': 'Loading...',
  'vehicle.noData': 'Vehicle data not found',
  'vehicle.frontPhoto': 'Front Photo',
  'vehicle.backPhoto': 'Back Photo',
  'vehicle.leftPhoto': 'Left Photo',
  'vehicle.rightPhoto': 'Right Photo',
  'vehicle.selectPhoto': 'Select Photo',
  'vehicle.takePhoto': 'Take Photo',
  'vehicle.chooseFromGallery': 'Choose from Gallery',
  'vehicle.cancel': 'Cancel',
  
  // Add Expense Page
  'expense.title': 'Add Expense',
  'expense.expense': 'Expense',
  'expense.type': 'Expense Type',
  'expense.typeRequired': '(Required)',
  'expense.price': 'Price',
  'expense.uploadReceipt': 'Upload Receipt',
  'expense.clickToTake': 'Click to take or select',
  'expense.receiptPhoto': 'receipt photo',
  'expense.addMore': 'Add Expense',
  'expense.submitButton': 'Add Expense',
  'expense.confirmTitle': 'Confirm Add Expense',
  'expense.totalAmount': 'Total Amount',
  'expense.baht': 'Baht',
  'expense.checkDetails': 'Please check details before proceeding',
  'expense.cancel': 'Cancel',
  'expense.confirm': 'Confirm',
  'expense.saving': 'Saving...',
  'expense.fillAllFields': 'Please fill in all fields',
  'expense.fillAllFieldsDesc': 'Please select type, enter price, and upload receipt',
  'expense.success': 'Expense Added Successfully',
  'expense.successDesc': 'Saved all expenses',
  'expense.error': 'Error',
  'expense.errorDesc': 'Unable to save expense',
  'expense.tollFee': 'Toll Fee',
  'expense.portFee': 'Port Fee',
  'expense.parkingFee': 'Parking Fee',
  
  // Change Password Page
  'changePassword.title': 'Change Password',
  'changePassword.newPassword': 'New Password',
  'changePassword.confirmPassword': 'Confirm Password',
  'changePassword.passwordMatch': 'Passwords match',
  'changePassword.passwordMismatch': 'Passwords do not match',
  'changePassword.usePassword': 'Use this password',
  'changePassword.changing': 'Changing password...',
  'changePassword.success': 'Password Changed Successfully',
  'changePassword.successDesc': 'Please log in with your new password',
  'changePassword.error': 'Error',
  'changePassword.errorDesc': 'Unable to change password',
  'changePassword.invalidData': 'Invalid data',
  'changePassword.minLength': 'Password must be at least 6 characters',
  
  // Forgot Password Page
  'forgotPassword.title': 'Forgot Password?',
  'forgotPassword.subtitle': 'Enter your registered phone number',
  'forgotPassword.phone': 'Phone Number',
  'forgotPassword.phonePlaceholder': '081 234 5679',
  'forgotPassword.phoneFormat': 'Please enter a valid 10-digit phone number',
  'forgotPassword.confirmButton': 'Confirm',
  'forgotPassword.signInButton': 'Sign In',
  'forgotPassword.backButton': 'Back',
  'forgotPassword.phoneVerified': 'Phone Verified',
  'forgotPassword.phoneVerifiedDesc': 'Please create a new password',
  'forgotPassword.error': 'An error occurred. Please try again.',
};
